### ISSUE TITLE
infinited animation?

### ISSUE THREAD

**Issue by netlarico** [maxwellito/vivus#101]
how can i replay the animation infinity mode? its possible?

regards,

**Comment by maxwellito** [comment]
How infinite? Rewind then play again? Reset and play?

This question has already been asked. Please check the other issues. If you
can't find it I'll help you :)

**Comment by netlarico** [comment]
Ohhh, you're right, i found the solution here:  
https://github.com/maxwellito/vivus/issues/97#issuecomment-210867653  

Thankssss
