### ISSUE TITLE
Drawing speed

### ISSUE THREAD

**Issue by hailie-rei** [maxwellito/vivus#102]
Hi! 

First of all, thank you for this plugin! It's really easy and useful. 

But I have one question. Is there a possibility to set a drawing speed? The problem is that I have a set of svg files, and some of them are short to draw and some of them have a lot of paths. So small svg files are drawing very slow, and big ones are drawing very quick, that is not suitable for my purpose.

I'll appreciate any advice! Thanks! 

UPD. For now I use this trick: I set this value as a duration: pathsCount * 25 (pathsCount is an amount of paths in my svg file). It's not exactly what I'd like to have, but it's better than nothing :)

**Comment by maxwellito** [comment]
Hallo,
Sorry for the delay, it's a tricky one because there's no way to do it without hacking the library. I would say, in `src/vivus.js` in the `mapping` method.

```js
  ...
  totalLength = totalLength === 0 ? 1 : totalLength;
  this.delay = this.delay === null ? this.duration / 3 : this.delay;
  this.delayUnit = this.delay / (paths.length > 1 ? paths.length - 1 : 1);
  this.duration = totalLength / this.duration; // << Add this line

  for (i = 0; i < this.map.length; i++) {
  ...
```

Then use the `duration` as speed:

```js
var fastAnim = new Vivus('hi-there', {duration: 10});
var slowAnim = new Vivus('hi-there', {duration: 1});
```

Not sure if it's clear, but don't hesitate to disturb :)

**Comment by hailie-rei** [comment]
@maxwellito Thank you for your comment! For now I just left my solution from my first comment, but I'll keep in mind your advice :)
