### ISSUE TITLE
vivus + grunt build dosent work

### ISSUE THREAD

**Issue by amitrahav** [maxwellito/vivus#105]
hey, when i use vivus for a yomen webapp project.
on grunt serve, vivus dosent create object tag wraping svg file:

`var need = new Vivus('need', {
		file: 'images/need-all.svg',
		onReady: function (myVivus) {
		    $(myVivus.el).addClass('finished').css({
		    	// 'bottom': 0,
		    	// 'top' : 'auto',
		    	'height' : 'auto',
		    });
		}	    
	});`

when i'm using grunt build, object tag wraping my svg, and it dosent animate.

**Comment by maxwellito** [comment]
Hey, got any errors in your browser debugger? (In Chrome, open devlopper
tools, then go to the 'console' tab)

**Comment by amitrahav** [comment]
Nope. No errors specifically about vivus.

**Comment by maxwellito** [comment]
Have you tried without your builder? Can you make a jsfiddle? Check that
your SVG is visible and displayed

**Comment by amitrahav** [comment]
ok, i'm getting 
`Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLObjectElement': Blocked a frame with origin "null" from accessing a frame with origin "null". Protocols, domains, and ports must match.`

after a lot of reading i found out its a chrome problem with same-origin frame.
my question is why there;s need to wrap svg with object tag on build?

**Comment by maxwellito** [comment]
Because it load it and build the DOM, then Vivus pick the SVG tag and move
it to your page (and delete the object tag). No need of an external library
to load the file.

**Comment by maxwellito** [comment]
Any help?

**Comment by amitrahav** [comment]
ya, it helped.
the issue was the the cross-origin loading iframe.

its fine on proddaction : http://monita.appsecure.co/

2016-05-15 1:11 GMT+03:00 maxwellito <notifications@github.com>:
