### ISSUE TITLE
Side effect in the mapping method for the 'scenario-sync' and 'scenario' cases

### ISSUE THREAD

**Issue by jimshell** [maxwellito/vivus#106]
Hello,

First of all congrats and thank you for this excellent lib! Very, very useful and efficient :-)

Sorry for not pull-requesting on this, I don't have my computer with me and cannot git anything easily on the computer I'm currently using...

I noticed an annoying side effect in the mapping method while using 'data-ignore' paths, which is due to using the 'paths' array within a loop on the 'this.map' array. Obviously, when setting 'data-ignore' for some paths, they're just not "in sync" any longer in terms of indexes. So, instead of:

```
case 'scenario-sync':
    path = paths[i];
    ...
```
and
```
case 'scenario':
    path = paths[i];
    ...
```

you should simply have:

```
case 'scenario-sync':
    path = pathObj.el;
    ...
```
and
```
case 'scenario':
    path = pathObj.el;
    ...
```

as 'pathObj' is assigned at the top of the 'this.map' loop (`pathObj = this.map[i];`)

__________________
Side note // nothing related to this side effect:

In order to have Vivus play nice with `<use>` tags that refer to def paths through the xlink:href attribute, I somewhat altered the 'mapping' method and everything works as expected:

```javascript
Vivus.prototype.mapping = function () {
    var i, paths, path, pAttrs, pathObj, totalLength, lengthMeter, timePoint, refPaths, pathLength, pathID;
    timePoint = totalLength = lengthMeter = pathLength = 0;
    refPaths = {};
    paths = this.el.querySelectorAll('path, use');

    for (i = 0; i < paths.length; i++) {
    path = paths[i];

    if (pathID = path.getAttribute('xlink:href')) {
        pathLength = refPaths[pathID];
    } else {
        pathLength = Math.ceil(path.getTotalLength());
        if (pathID = path.getAttribute('id')) {
            refPaths['#' + pathID] = pathLength;
        }
    }

    if (this.isInvisible(path)) {
        continue;
    }

    pathObj = {
        el: path,
        length: pathLength
    };

    if (isNaN(pathObj.length)) {
        ...
```

The reference paths should obviously be set prior to using them (in a `<defs>` section ideally), with a proper 'id', and be used the regular way, for instance:

```
<defs>
    <path id="mypath" data-ignore="true" d="..."/>
</defs>
<g class="group-class">
    <use x="0" y="0" xlink:href="#mypath"></use>
    <use x="100" y="0" xlink:href="#mypath"></use>
    <use x="50" y="50" tranform="scale(.5,.5)" xlink:href="#mypath"></use>
</g>
```

Note the 'data-ignore=true' on the def path: if you do not set it, the def path will be "animated" too first (though not visible) => the 'stroke-dasharray' and 'stroke-dashoffset' styles will be assigned onto it, making the `<use>` tags' styles useless (not interpreted, they won't be animated)

It works a treat on webkit browsers: Chrome, iOS safari (from iOS 6 - haven't tested it on FF or IE, but I assume that if it doesn't work on those, it would probably be related to how they handle SVG than to the above code...). I've used `<use>` tags in a 'scenario' context, and everything plays fine and smoothly, allowing less SVG code/duplication for redundant paths.

Cheers,
Jimshell

**Comment by maxwellito** [comment]
Hallo,
Thanks for these kind words and this nice and well detailled issue.

For the first part Ill have a look once at my desk.

For the second part, I'm not sure to follow. Long time ago somebody asked
me about the use of `use` tags. After few test I realised that these
elements are just a replication of the original dom, but aren't
independant. You can't define a specific `stroke-dasharray` to a `use` tag.
So, in your example, why don't you remove the `data-ignore` and let the
animation play?
Sorry if Im completely wrong :-S its what I understood. Otherwise, provide
me a jsFiddle. Examples you can hack makes things easier to understand ;)

Thanks

**Comment by jimshell** [comment]
Hello,
Thanks for your quick reply :) And you're welcome, all deserved.

For the first part, it was not obvious that there was something strange, it only showed up when I began to use several 'data-ignore' paths with regular paths, and noticed that some paths were not apparently doing anything, then I checked the map and realized that there were "gaps".

For the second part: I'm not sure about how browsers consider `<use>` tags, actually. And you are right to say that they're not indepedent, as they refer to a unique def path. I did test first a simple animation, of 'async' type: it just work whether 'data-ignore' is set or not on the def path (but it **does** compute the animation for this 'invisible' path too, which is overkill, isn't it?), what is sure is that, in Webkit browsers, you definitely can define specific `stroke-dasharray` to `<use>` tags, and it works really well (tested in Chrome for Windows and Android, and in iOS 6 Safari - yeah, quite old, but used for testing purposes ^^)

My secondary tests involved the 'scenario' type, and then it just didn't work as expected: indeed, it did seem that the def path "state" was somewhat interfering with the `<use>` tags if no 'data-ignore' was set on the def path. I've put together the following jsfiddle for you to have a look at what's happening in both cases (**important note**: i've included my modified version, minified. It was simplified to work with Webkit browsers only, so this fiddle will not work with FF or IE or anything but a Webkit browser) => https://jsfiddle.net/wzmaxv4e/1/

As you'll see, the first animation doesn't play well: as path are drawn, you'll notice that start/end don't fit the actual path length. It's maybe just due to the way path calculation is implemented in Vivus, but I think it's not worth it to 'break', possibly, something that works well overall for just a very specific use case, as it is just enough to set 'data-ignore' on the def path to have `<use>` tags behave properly.

Please let me know your thinks on this :)

**Comment by maxwellito** [comment]
Hallo,

Apologies for the delay. It's a shame to make a contributor wait so long when he got good points and take time to explain them.

1. I checked Vivus code, then understood what you mentioned. That was my face when I got it:
![](https://media.giphy.com/media/aKYpYXhR6kH1S/giphy.gif)

So, one thing: Well spotted! Thank you!! I need to patch this

2. le `<use>` tag
Thanks for the examples. I guess you became as skeptical as I am about this tag. The implementation vary across platform which makes it too clunky to be used on this library. I mean, on Firefox it works like a charm, but on Chrome it's absolutely awful to watch. However, maybe we can make a section in the `hacks.md`.

Btw, the path calculation is done by the browser with `.getTotalLength()` on the path object.

**Comment by jimshell** [comment]
Hi !

Oh no worries, there is no hurry at all ^^

^^ i know that feeling, it happens to me (much too) frequently ^^. But honestly it was not obvious, I really had to play with a very specific combination ('scenario' + 'data-ignore') to notice the gaps and then have a proper read to the code to spot it. Glad I could help on this :-)

Yes, absolutely: skeptical is the right term ^^
I haven't tested in Firefox, but I'm surprised about your tests/results in Chrome actually: here (latest Chrome / Windows 10, Android Lollipop latest Chrome / latest android webview, and even iOS Safari - from iOS 6 to to iOS 9), results are beautiful, really O_o Performance on my iOS 6 test device (an old iPhone 4) has even been improved - primarily because of the same path not being repeated several times in the SVG markup, according to me.
But to be sure that I understand : did you compare FF and Chrome `<use>` tag usage on a test of your own, or with the jsfiddle I provided?

Ah yes sorry, turned my sentence a strange way, having in mind that in Snap Svg for instance, they do the maths not to rely on the `getTotalLength()` implementations in browsers. I studied my fiddle's behaviour a bit more, at a slower speed, and it appears it has nothing to do with path lengths: the def path being applyed styles does interfere with the `<use>` tags' own styles. It sort of overrides them: their `stroke-dashoffset` start value equals the def path's `stroke-dashoffset` value at the time the `<use>` tags start to be animated (very clear if your play my jsfiddle at a slower pace) 'data-ignore' does solve this as the def path is no longer being animated at all (no styles, no overriding)

Please let me know about your clunky results in Chrome - Chrome / webkit are my absolute targets for my current project, any clue on a possible flaw will always be much appreciated :-)

Jimshell

**Comment by maxwellito** [comment]
Hi there,

Yes I tried you jsFiddle in Chrome and Firefox. I made some test on the `<use>` tag long time ago and I concluded that the tag is implemented correctly but each `use` tag is a duplicate from the original node and they have no freedom. If the original node got a `stroke-dasharray` property, it will be replicated on the `use` nodes. But the `use` node cannot have his own `stroke-dasharray` property. 
However, after what you show me I think I was incorrect (or things have changed). 

About SnapSVG I didn't know. I should have a look to this.

I'll come back to you once I got results :)

But thanks again for this, your analysis is quite helpful!

**Comment by jimshell** [comment]
Hi there :)

Sorry for replying late.

You are totally right: `<use>` tags do inherit the def path style, thus do inherit the `stroke-dasharray` property, and this is why, as I could check, a `data-ignore` property on the def node does the trick => that way, each `<use>` tag style is independent from the original node because it just has no style at all ;) This is what can be seen in the jsfiddle that I put together.

You are most probably right saying that things have changed => it's likely to be correct that the orignal behaviour was entirely dependent on the original node, and browsers implementations must have been improved so that the `<use>` tags are not that dependent on their reference (DOM-wise, it wouldn't be 'spec compliant' to have nodes you can't operate on granularily just because they refer to some other node)

Snap SVG is definitely not as lightweight as Vivus ; but this lib does work well, and I found their code pretty neat and efficient.

Please do, when you have a chance :) I'll let you know if I ever notice anything new that could help in anyway :)

You're welcome, and thanks again for Vivus which is really excellent and what I need right now ^^

Cheers,
Jimshell
