### ISSUE TITLE
late callback 

### ISSUE THREAD

**Issue by RUIFERNANDE5** [maxwellito/vivus#107]
`new Vivus('mascot', {
        duration: 400,
        start: 'inViewport',
        animTimingFunction: Vivus.EASE,
        file: '/assets_img/concept/AW_Mascote_Clappyu.svg'
    },  function(){
        $('section.fun-info > div').addClass('ready');
    });`

My callback is adding the class 'ready' ~5 seconds after the path stops drawing, is it a bug or am I doing something wrong?

Thanks in advance!

**Comment by maxwellito** [comment]
You probably have some invisible paths which are drawn. Be sure your SVG
doesn't contain any "display:none" tags.

**Comment by RUIFERNANDE5** [comment]
It did not contain any "display:none" tags. My svg had only a unique compounded path though, I did export the svg again as multiple paths and it did work. 
Thank you!
