### ISSUE TITLE
Path animation not working in Chrome

### ISSUE THREAD

**Issue by JasonStorey** [maxwellito/vivus#109]
The following fiddle works in FF, but doesn't animate in Chrome 51. Weird thing is, it animates fine in Chrome when the dev tools are open!

https://jsfiddle.net/gmz622e1/1/

**Comment by maxwellito** [comment]
The animation starts when the SVG is visible in the viewport. Just scroll and it will start.

**Comment by JasonStorey** [comment]
I see, thanks! I hadn't realised that it waits for the SVG to be within the viewport by default. I see the `start` option now.

What counts as 'viewable'? The animation doesn't appear to trigger when 90% of the SVG is on screen.

**Comment by maxwellito** [comment]
Hey,
Sorry about the delay. Vivus consider an SVG to be in the viewport when this one fit entirely in the current viewport. 

If you want to change this behavior, you will have to hack the library ;) Just look at `src/vivus.js` at the line 470 (or `dist/vivus.js` line 722 if you don't want to go through the recompiling system). The trigger to start the animation check `isInViewport` function. The second parameter is the percentage of the SVG which must be visible to consider it as 'inViewport`. Just play with it.

**Comment by JasonStorey** [comment]
That's great, thanks.
