### ISSUE TITLE
Support of property vector-effect="Non-scaling stroke"

### ISSUE THREAD

**Issue by M4n1ok** [maxwellito/vivus#112]
Hi, 
I have some problems with SVG which contains property vector-effect="Non-scaling stroke"  for responsive design. When i applied this, stroke and animate have some gaps. I think that there is a problem with calcul of length path for dash-array and dash-offset. 

Do you have an idea to fix it ?
Thanks a lot :)

**Comment by maxwellito** [comment]
Hello,
I have to admit I have never used this property. Can you provide me an example about this problem? Also, can you tell me more about your browser (and version) and the version of Vivus you're using?
Thanks

**Comment by M4n1ok** [comment]
Hello, 
This property comes with svg tiny (1.2) and enables stroke to keep his aspect (stroke-width) when you resize SVG. 
Normally, vector-effect is supporting by recent browser. I have realized some test on last version of chrome and firefox. When you use vector-effect without Vivus, it's works. SVG strokes keep their aspect on resize. 
But when i want to couple with Vivus (last version), path are animated with space and draw is realized not fully like if the calcul of path length will be wrong. 
Thanks

**Comment by alexgurr** [comment]
I have this issue too. What a shame!

**Comment by maxwellito** [comment]
@alexgurr : Hey hunny, pull requests are always open ;-)

**Comment by alexgurr** [comment]
Hi Max. I've fixed this in my local copy of vivus. Will open a PR for the fix :)
