### ISSUE TITLE
Security Error  on Chrome

### ISSUE THREAD

**Issue by sakulbudhathoki977** [maxwellito/vivus#114]
Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLObjectElement': Blocked a frame with origin "null" from accessing a frame with origin "null". Protocols, domains, and ports must match.

It works fine in firefox.

**Comment by maxwellito** [comment]
Are you sure to use the same domain and protocol? Using 'file:///' might
not be recommendable.

**Comment by sakulbudhathoki977** [comment]
Thank you it works on xampp. I used it without a server.
