### ISSUE TITLE
Unable to animate other paths

### ISSUE THREAD

**Issue by aneeshjajodia** [maxwellito/vivus#115]
Hello,

I've been trying to set all of this, but was unable to animate the other paths other than the first one.

Please have a look here. www.lomdi.in, the footer, the stamp.
<img width="278" alt="screenshot 2016-06-29 19 07 59" src="https://cloud.githubusercontent.com/assets/1062704/16454069/c95aa5ca-3e2c-11e6-87c8-23320204d521.png">

**Comment by maxwellito** [comment]
Hallo,
Vivus is acting as normal. Your SVG is just not based on `stroke` but `fill`. I set the fox with a red stroke:

![screen shot 2016-07-01 at 00 36 45](https://cloud.githubusercontent.com/assets/1097232/16507729/12730afc-3f24-11e6-98f2-efd7d2c62ee3.png)

You must make your SVG with strokes only to animate it with Vivus.
