### ISSUE TITLE
Custom delay for each path, in javascript

### ISSUE THREAD

**Issue by Snofinity** [maxwellito/vivus#117]
Hello,

I've had great success with vivus so far, but I'm stuck on one thing. I want to specify the delay of each path separately, rather than having each path draw at relatively the same time with the "oneByOne" animation. Here's my current code:

new Vivus('my_svg_div', {
	type: "oneByOne",
	duration: 400,
	file: './animation.svg',
	onReady: function (myVivus) {
	        myVivus.el.setAttribute('width', '614px');
	        myVivus.el.setAttribute('height', '603px');
        }
});

As you see, I'm creating the object in Javascript rather than in the HTML, since my svg file is pretty complicated. I saw how you can scenarize it, but it looks like you do that in the HTML. I don't want to write the svg file with the paths in the HTML, since like I said my file is large.

Is there any way I can use Javascript to scenarize the vivus object, rather than typing out each path in the HTML?

Thanks!

**Comment by maxwellito** [comment]
Hello,
I'm afraid but using `scenarize` is the only way, so touching the SVG code.
However, you can modify the `.map` property of your Vivus instance before you run the animation. Doing it on the `onready` callback should be good.

**Comment by Snofinity** [comment]
Alright, I'll look into that. Thanks!
