### ISSUE TITLE
Using vivus with img tag

### ISSUE THREAD

**Issue by stewsmith** [maxwellito/vivus#12]
The HTML:
`<img id="graph" src="graph.svg">`

and Javascript:
`new Vivus('graph', {type: 'delayed', duration: 200});`
or:

```
var g = document.getElementById('graph');
new Vivus(g, {type: 'delayed', duration: 200});
```

Results in:
`Uncaught Error: Vivus [contructor]: "element" parameter must be a string or a SVGelement`

**Comment by timelyportfolio** [comment]
for reference, I found this also http://benhowdle.im/deSVG/
