### ISSUE TITLE
Improve display speed and smoothness

### ISSUE THREAD

**Issue by crouti** [maxwellito/vivus#120]
Hi there,
Thank you very much for your nice library !! :)
Can you please explain me how i could speed up display of the following pics, my SVG files seem too big, but maybe i do't use your lib correctly : http://www.maxunger.fr/
It's particularly slow on mobile devices (tested on iphone 5)
Thank you very much

**Comment by maxwellito** [comment]
Hi,
Thanks for these kind words :)
However, I no longer accept issues without a JSfiddle to check the problem. It's a requirement. If you have a question about how to use Vivus, you better join the conversation on Gitter :)
