### ISSUE TITLE
Vivus-specific SVG Path preparation guidelines/readings

### ISSUE THREAD

**Issue by daedelus-j** [maxwellito/vivus#121]
I guess this is probably more of a general SVG knowledge question. But since you're library has chosen the stroke offset approach for paths, it'd be nice to include SVG preparation readings.

For this specific instance, the example svg below uses paths, but the library draws strokes around both sides of the paths leading to an undesired animation effect. How do I prepare the paths so it looks like a single stroke? I assume it's part of the svg export process.

Thanks!

**Vivus version**:
0.1.3

**JSFiddle link (or similar platform)**:

https://jsfiddle.net/b18kvopL/2/

**Comment by maxwellito** [comment]
Hi,
This depends on the way you've been creating the illustration in your editor.
For example, in Illustrator, the brush create paths, the pen create lines.
The only way I would transform your SVG example into simple lines would be to delete points on path to make each shape a simple line. But you will need to edit it yourself. I don't think there's a magic program to help you with, but if you find one please post it here :)

**Comment by daedelus-j** [comment]
Thanks for the reply! I wasn't wanting a magic program :) But perhaps more reading on optimizing exports for your library.

**Comment by maxwellito** [comment]
Hehe :) You're welcome. I should put a tutorial about how to create an optimised SVG for Vivus. (I take note)

**Comment by daedelus-j** [comment]
haha Well actually, that brush vs pen advice is extremely helpful at the moment :)
