### ISSUE TITLE
How to draw path and then animate fill?

### ISSUE THREAD

**Issue by studioleland** [maxwellito/vivus#122]
### Please define your problem or issue as clear as possible.

For a problem, please fill the following:

**Vivus version**: Latest

**Browser**: Chrome

**Steps to reproduce it**: Just curious about best way to accomplish this

**JSFiddle link (or similar platform)**:
*No personal website will be allowed, only sandboxed platform where the code is isolated and can be hacked.*

*[note]*
Please have a minimum of politeness. There's unfortunately only me as contributor/maintainor which help on my free time, I'm not the Amazon customer service or your Mom. I don't ask to send me flowers and tell me how amazing Vivus is (that won't make me help you quicker). But please try to do as much as you can before opening an issue: check that no closed issue mention a similar problem, that your script is executed correctly (conflicts, race conditions...).. Thanks :)
Otherwise I will take a delighted pleasure to reply with `RTFM` or `Learn JavaScript you f***** moron``
*[/note]*

**Comment by maxwellito** [comment]
Hi there,
I'm sorry issues are reserved for bugs, making your ticket invalid.
If you have any questions about how to use the library, please join the conversation on Gitter.
However, for your problem you better check the [Hack page](https://github.com/maxwellito/vivus/blob/master/hacks.md#animate-fill-with-css)
