### ISSUE TITLE
Question: how to dynamically reload with different file?

### ISSUE THREAD

**Issue by KrishnaPG** [maxwellito/vivus#123]
After loading an SVG, need to replace it with another SVG on click of button (something like a slide-show, so to speak).

What is the recommended way to achieve this? What should be safe order of calls, such as `stop`, followed by `destroy` etc.  or just create a new object without worrying about the old one? Concerned about any memory leaks etc.

**Comment by maxwellito** [comment]
Yes, `stop()` and `destroy()`. Then create a new object. The old one can be garbage collected.

**Comment by KrishnaPG** [comment]
Does `destroy()` cleanup the DOM? Looks like it is not. What is the right method to cleanup the DOM so that next SVG can be placed in the same location?

**Comment by maxwellito** [comment]
I just does the necessary to to make the object garbage collected
correctly. Its your job to remove/edit your DOM.

2016-08-17 10:21 GMT+01:00 Gopalakrishna Palem <notifications@github.com>:

**Comment by KrishnaPG** [comment]
It is not working - freezing the browser.

Below is the code, that tries to replace existing loaded SVG with another one:
````
		function cleanSVGDOM(svgContainerID, svgObj)
		{
			svgObj.stop();
			svgObj.destroy();
			svgObj = null;	
			var svgContainerNode = document.getElementById(svgContainerID);
			while (svgContainerNode.firstChild)
   			 svgContainerNode.removeChild(svgContainerNode.firstChild);			
		}

		if(self.schematicSVG)
		     cleanSVGDOM('floor-schematic-svg', self.schematicSVG);
					
		self.schematicSVG = new Vivus('floor-schematic-svg', { file: self.floorData.plan });		

````

In the debugging, it appears that no need to call `stop` and then `destroy`, since the destroy code is already calling the `stop` as below:
````
Vivus.prototype.destroy = function () {
  this.stop();
  var i, path;
  for (i = 0; i < this.map.length; i++) {
    path = this.map[i];
    path.el.style.strokeDashoffset = null;
    path.el.style.strokeDasharray = null;
    this.renderPath(i);
  }
};
````
For that matter I do not see the reason to call `destroy` at all, given that for a dynamically loaded SVG (from file), to replace it with another svg, we have to clean the whole the SVG tree.

After cleaning the SVG DOM and loading a fresh one from file as show in my above code, the browser is just freezing.

**Comment by KarmaBlackshaw** [comment]
Good day! I am having the same problem, have you found the solution to completely destroy the svg ? I also load dynamic SVG on click event.

**Comment by curlyz** [comment]
```javascript
// place a div in your structure with id
let vivus = Vivus( "yourid" , options , callback );

// reload
vivus.stop();
vivus.destroy();
document.getElementById('yourid').innerHTML = "";
```
