### ISSUE TITLE
Safari not loading

### ISSUE THREAD

**Issue by Sam116** [maxwellito/vivus#124]
Using last version of vivus. In Safari on PC, Mac, Ios page can't load with draw script, some svg icons are working, but some breaks the page.  For example https://jsbin.com/quvakiqivo/edit?html,js,output. What it can be connected with?

**Comment by maxwellito** [comment]
Your SVG is the issue. The path elements for the 'cove' seems too complex for Safari (which could be simplified, I don't know why there's so many points to define them). When it call the method `getTotalLength()` on these paths, my Safari crashes, litterally. 

I made a copy of your jsbin without the coves, and it run as it should be.
https://jsbin.com/wafehupaja/1/edit?html,js,output

Try to redraw these path with your graphic editor, or simplify these paths with [SVGOMG](https://jakearchibald.github.io/svgomg/)
