### ISSUE TITLE
Erase effect?

### ISSUE THREAD

**Issue by yellow1912** [maxwellito/vivus#126]
Hello,

This is not a bug report. I just wonder if it is possible to have the erase effect. Les say Im drawing a rectangle with 4 paths and when I reach path 2 I want to start erasing path 1 so it looks kinda like a the rectangle is drawn more at the end and erased at the beginning.

**Comment by maxwellito** [comment]
Mmmm.. I'm not sure to understand what you want to achieve. Can you draw something, or make a schema please?
Also, because this is not a bug, let's continue on [Gitter](https://gitter.im/maxwellito/vivus).
