### ISSUE TITLE
Rename async to something else

### ISSUE THREAD

**Issue by AshleyGrant** [maxwellito/vivus#131]
### Please define your problem or issue as clear as possible.

**Vivus version**: 0.3.2

**Browser**: all

I saw this project posted on /r/javascript. I just wanted to start a dialogue regarding the `async` method. I think it's confusingly named. I know that in programming `synchronous` means to do things one after another, while `async` means, well, to do them as things happen (via callbacks or using promises or `async`/`await` in JS). 

But when I think about what the drawing method that is used when calling `async` in this library, it reminds me of marching bands and synchronized swimming and such. The lines are drawn in a synchronized fashion. So I feel like `async` is a confusing name.

I'm not here to crap on this project or anything, I just thought it'd be good start a dialogue on this before the project hits 1.0 and the name can't easily be changed.

Thoughts?

**Comment by maxwellito** [comment]
Hallo,
Don't worry, you're not the first and not the last :) However I could
change the name without being destructive (so the 'async' would continue to
work).
But the question is : what new name shall I give to this type?
Are the other names ok?

**Comment by AshleyGrant** [comment]
I'll list some options. Hopefully some other people will get in here and throw a ruckus about how bad my suggestions are.

- `sync`
- `synchronized`
- `atTheSameTime`
- `allTogether`
- `justinTimberlake` (get it, b/c everything is drawn "n'Sync")

Ok, so that last one is a joke, and the other ones all have flaws. But if we've got `OneByOne` then `AtTheSameTime` might work. 

As far as the other names, I think they're fine, but that's just, like, my opinion, man.

**Comment by maxwellito** [comment]
Dammit! I wanted to discretely pass the `nsync` in the types list. But you
got the idea before... let's put it anyway :)
About the naming, I saw something on Reddit I quite like : parallel. It's
simple and really describe my vision of it.
Do you find it alright? I just want to stay away from 'sync'.

I wanted to keep 'delayed', and maybe rename the 'oneByOne' to something
like 'queue'.

>

**Comment by AshleyGrant** [comment]
I'm cool with `parallel`.

**Comment by StoneCypher** [comment]
I just came here to file this.

Parallel seems incorrect.  It implies that multiple distinct jobs are being done, which will terminate with distinct gathered results and may not take the same amount of time.

This is `.sync()`. No question.

**Comment by Harryandrew** [comment]
+1 AshleyGrant!

I was banging my head for a moment looking at `Async` - otherwise great job

**Comment by maxwellito** [comment]
Thanks to @Harryandrew and @AshleyGrant for your comments. I would like to have other people points of views about it.

However I would like to say to @StoneCypher that I don't tolerate your behavior (here and on Gitter). True, I made a mistake by badly naming this animation type, ok. And I don't wanted to change the API until I move to the next major version to avoid breaking changes. But laughing at me, writing `FILING THE MOST PASSIVE AGGRESSIVE BUG`, and imposing your views without talking by finishing your message by `No question.`. Oh boy....

**Comment by StoneCypher** [comment]
> However I would like to say to @StoneCypher that I don't tolerate your behavior (here and on Gitter)

Yeah, I didn't actually do the things you're angry about

> True, I made a mistake by badly naming this animation type, ok.

I never said you did anything bad.  People commenting on other peoples' mistakes is normal in open sources.

> And I don't wanted to change the API until I move to the next major version to avoid breaking changes. 

Okay.  I didn't say anything about this

> But laughing at me

I never laughed at you

> writing FILING THE MOST PASSIVE AGGRESSIVE BUG

This is me criticizing myself, not you.  Why are you angry about my saying "hey, I'm filing a bug over a minor detail?"

> and imposing your views without talking by finishing your message by No question.

Yeah, if being politely told that there's actually a right and wrong to technical terminology is offensive to you, then good luck in open source

I have absolutely no idea what you're angry about, to be frank.

Let me know if you want any of the bugfix PRs I made last night.  I'm betting "no."

**Comment by maxwellito** [comment]
@StoneCypher : let's continue in PM on Gitter.
Everybody else, sorry about the interlude.
