### ISSUE TITLE
Can you play an animation in reverse?

### ISSUE THREAD

**Issue by zfrenchee** [maxwellito/vivus#132]
I have drawn something in my editor backwards. Is there a way to elegantly fix this mistake and draw the svg path from "back to front" or "end to beginning". I'm not asking to "undraw" the svg -- which is what I think others are talking about when they mention "reverse" animation in the issues.

**Comment by StoneCypher** [comment]
Seems like it'd probably be a lot easier to just fix the SVG using javascript.  Wrote this off the top of my head and haven't tried it; it's probably buggy, but it should be roughly what you need.

```html
<!doctype html>
<html>

  <head>

    function FixThePics(broken, fixContainer) {

      var allElem = broken.getElementsByTagName("*"),
          total   = allElem.length;

      for (var i = 0; i < allElem.length; i++) {
        fixContainer.appendChild(allElem[total-i].cloneNode);
      }

    }

    window.onload = () => {
        FixThePics(document.getElementById('original'), document.getElementById('repaired'));
        debugger; // now inspect repaired, get the .outerHTML, and save it to disk
    }

  </head>

  <body>
    <object id="original" data="thePain.svg" type="image/svg+xml"></object>
    <svg id="repaired"></svg>
  </body>

</html>
```

**Comment by zfrenchee** [comment]
Thanks! I ended up fixing the svg ;)
