### ISSUE TITLE
Microsoft Edge script error

### ISSUE THREAD

**Issue by dbdev** [maxwellito/vivus#134]
Hi,

I'm been battling for quite a while now with a very strange issue that's occurring only with Edge browser.

**Vivus version**: 0.3.1 (but even with 0.4 it's the same)

**Browser**: Edge 13/14

**Steps to reproduce it**: The issue can be found here with Edge https://undsgn.com/uncode/homepages/creative-studio/

I've tried to just use the JSFiddle but I'm getting an error there (look you will understand what I mean), so I had to post the URL. In the JSFiddle you can anyway see how I'm using Vivus

**JSFiddle link (or similar platform)**: https://jsfiddle.net/8hs5uyos/

I'm testing on a Windows 10 machine and either Edge 13 and 14 are not working.

Just keep in mind that I'm using your library on a theme used by over 13.000 sites, so potentially this issue is widely spread. 

Thanks

**Comment by maxwellito** [comment]
Ok, Im downloading a VM and I'll test it. I guess the problem is about the
4 icons, right? (Advanced grid/digital branding/top performance/responsive
design)

**Comment by dbdev** [comment]
Yes exactly

**Comment by maxwellito** [comment]
Ok it will take me more time than I thought. My personal machine even struggle to display the page correctly. Half of the content is missing. I will be back when I will put my hand on a more powerful machine.

**Comment by dbdev** [comment]
If you want I can give access to my account of browserstack to debug it.

Let me know.

**Comment by maxwellito** [comment]
Ermm... That could be helpful :)
Probably tonight (quite late) I should have a spare moment to look at it

2016-11-14 16:32 GMT-05:00 dbdev <notifications@github.com>:

**Comment by dbdev** [comment]
Hi,

did you had the chance to check it?

Let me know if you need access to browserstack, send me an email to damiano@undsgn.com

**Comment by maxwellito** [comment]
*Ticket been discussed offline*
