### ISSUE TITLE
Starting point visible

### ISSUE THREAD

**Issue by MisterRoot** [maxwellito/vivus#135]
**Vivus version**:
v.0.4.0

**Browser**:
Mozilla Firefox and Google Chrome

**Steps to reproduce it**:
In Google Chrome and Firefox is the startpoint of the svg always visible. The only Browser where it works is Edge.

**Comment by maxwellito** [comment]
Hi there,
Can you please provide me an example? I tried the demo page with the latest Firefox (49) and Chrome (54), and I don't see any starting points :-S
Thanks
