### ISSUE TITLE
Automatically filling in the gaps of my svg

### ISSUE THREAD

**Issue by cup-of** [maxwellito/vivus#136]
Hello sorry to bother, and also sorry if I am in the wrong place.

I have an svg that contains some dashes with gaps in between them. I have the animation set up and working but the problem is that the animation fills these gaps and creates one single line. Is there a setting to prevent this? I tried my best to fix this, I've read the user guide many times but I still cant figure it out. Maybe its just my svg but I thought id ask for help before I blamed it on the svg.

Here is the JSFiddle link. [https://jsfiddle.net/1yp1ktwf/](https://jsfiddle.net/1yp1ktwf/)

The svg on the left is what it is supposed to look like, and the one on the right is the animated one. You will see the transformation.

In the js panel I included vivus.min.js and below that I created the instance of vivis.

Thanks!

**Comment by maxwellito** [comment]
Hi there,

I see your problem and this is one of the use case that is incompatible
with Vivus. This library use the `dashstroke` to fake the drawing
animation. So it cannot be applied on a path which already have a specific
dashstroke property.
I'm sorry about the bad news :(

**Comment by cup-of** [comment]
Aww ok, thanks for responding so quick!

**Comment by maxwellito** [comment]
Unfortunately no :(
Except cutting your SVGs in your editor to create real lines.
I did this to your jsfiddle :) https://jsfiddle.net/1yp1ktwf/2/

**Comment by cup-of** [comment]
YES!!! thank you so much sir! :D

**Comment by maxwellito** [comment]
You're welcome! ;-)
