### ISSUE TITLE
triggering question?

### ISSUE THREAD

**Issue by devinpruitt** [maxwellito/vivus#138]
Hi i just had a question not a problem. is there a way to trigger this with a button instead of scrolling?

**Comment by maxwellito** [comment]
Hi there,
Sure! Just set the option 'start:"manual"' then use the method ".play()" on
your instance when you're ready to start.

// Create the instance
var myVivus = new Vivus('mySVGid', {start:'manual' /* plus your other
options */});

// ...then later, on your click event
myVivus.play()
