### ISSUE TITLE
vivus.js

### ISSUE THREAD

**Issue by roldyclark** [maxwellito/vivus#139]
https://github.com/maxwellito/vivus 
Here's the lib. 
I npm installed it in both places, but couldn’t get require to work-
so I did a `<script src='vivus.js'>` right in the profile
and put the js in a few spots because I dont know how this hugo thing builds.

Styling should be all set though!

**Comment by maxwellito** [comment]
Hi there,
Im sorry but Im not sure to understand the problem. Are you trying to use
Vivus with requireJS?
