### ISSUE TITLE
Wrong format of SVG? Flaticon.com

### ISSUE THREAD

**Issue by Artimal** [maxwellito/vivus#140]
Hi, I am using:
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vivus/0.4.0/vivus.js"></script>
<script type="text/javascript" src="/js/pathformer.js"></script>
```

And SVG from flaticon.com:
```

<svg version="1.1" id="svg_branding" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 488.6 488.6" style="enable-background:new 0 0 488.6 488.6;" xml:space="preserve" fill="#DC005A">
<g>
	<g>
		<path d="M363.9,54.1C333.6,19.7,290,0,244.3,0S155,19.7,124.7,54.2C99.2,83,85.2,120.5,85.3,159.5s14.2,76.4,39.8,105.2
			c4.2,4.7,8.7,9.2,13.4,13.4c16.7,14.9,23.8,29.2,23.8,48l-0.2,18.7c-0.1,9.9,7.9,18.1,17.8,18.2c0.1,0,0.1,0,0.2,0
			c9.9,0,17.9-7.9,18-17.8l0.2-18.7v-0.1c0.1-29.4-11.3-53.2-35.8-75.1c-3.6-3.2-7.1-6.8-10.4-10.4c-41.2-46.4-41.3-116.4-0.3-162.9
			c23.5-26.7,57.3-42,92.6-42c35.4,0,69.1,15.3,92.6,42c40.9,46.4,40.8,116.3-0.1,162.6c-3.3,3.8-6.9,7.3-10.6,10.7
			c-24.1,21.5-35.4,45.1-35.5,74.1l-0.2,19.6c-0.1,9.9,7.9,18.1,17.8,18.2c0.1,0,0.1,0,0.2,0c9.9,0,17.9-7.9,18-17.8l0.2-19.6
			c-0.1-0.3-0.1-0.3,0-0.4c0.1-18.8,6.9-32.6,23.5-47.4c4.8-4.3,9.3-8.9,13.6-13.7c25.4-28.8,39.4-66.1,39.4-105.1
			C403.3,120.3,389.3,82.9,363.9,54.1z"/>
	</g>
</g>
<g>
	<g>
		<path d="M308.5,393.1H180.1c-9.9,0-18,8.1-18,18c0,9.9,8.1,18,18,18h128.5c9.9,0,17.9-8,17.9-18
			C326.5,401.2,318.4,393.1,308.5,393.1z"/>
	</g>
</g>
<g>
	<g>
		<path d="M278.9,452.6h-69.3c-9.9,0-18,8.1-18,18c0,9.9,8.1,18,18,18h69.3c9.9,0,18-8.1,18-18C296.9,460.7,288.8,452.6,278.9,452.6
			z"/>
	</g>
</g>
<g>
	<g>
		<path d="M257,211.1l-49.7-49.7c-7-7-18.4-7-25.5,0c-7,7-7,18.4,0,25.5l44.5,44.4c0,26.4,0,113.7,0,113.7c0,9.9,8.1,18,18,18
			c9.9,0,18-8.1,18-18V225.2C262.3,218.6,260,214.1,257,211.1z"/>
	</g>
</g>
<g>
	<g>
		<path d="M306.8,161.3c-7-7-18.4-7-25.5,0l-9.5,9.5c-7,7-7,18.4,0,25.5c3.5,3.5,8.1,5.3,12.7,5.3s9.2-1.7,12.8-5.3l9.5-9.5
			C313.8,179.8,313.8,168.4,306.8,161.3z"/>
	</g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
</svg>
```
What is wrong with that svg that event pathformer is not helping? If you will try to animate it by https://maxwellito.github.io/vivus-instant/ you will see only static version.

How can I fix that or maybe convert it to the right form? Please for help and thank you :)
Arthur

**Comment by maxwellito** [comment]
Hi Arthur,

Unfortunately your SVG is not compatible with Vivus. It's fill based
instead stroke based.
I see only two options:
- You must redraw your SVG with strokes in your graphic editor.
- Or use this hack
https://github.com/maxwellito/vivus/blob/master/hacks.md#animate-fill-with-css
to perform an animation on the outline (you will have to set a stroke value
on your paths)

I know it's not ideal. Unfortunately, most of icons available online are
never stroke based. Even if they look like it, their creators generate path
from the outline (which doesn't make sense in most of the case) turning
something stroke based into fill based. And there's no magic to go the way
back :(

Also, you don't need to include pathformer.js, it's already included in
vivus.js :)

**Comment by Artimal** [comment]
I don't udnerstand that "hack". It isonly about opacity... not aabout turning my fill based into stroke. I have Adobe Illustrator do you know how can I render svg in right options for vivus? I even made for you and others a little graphic with all options of svg. You can write me or check graphicly which options set.
Greatings maxwellito :)

**Comment by maxwellito** [comment]
Sorry about the delay, Im away from my computer. But I'll try to prepare
that tomorrow :)

**Comment by maxwellito** [comment]
Hallo again,
Here is the result of what I was talking about: http://maxwellito.github.io/drafts/vivus-issue-140/
You can see the code here https://github.com/maxwellito/drafts/tree/gh-pages/vivus-issue-140
I left some comments in `index.html`

**Comment by dfcreative** [comment]
@maxwellito I drag and drop your [svg](https://github.com/maxwellito/drafts/blob/gh-pages/vivus-issue-140/icon.svg) into vivus instant and it does not animate. Nor any of my cases. Is there any special svg config required to make it animate droped svg?
Thanks.

**Comment by maxwellito** [comment]
@dfcreative This is why I recommend, in this issue, to use Vivus.js + a hack. The default Vivus behavior won't animate this SVG. Which means vivus-instant won't either. 

Because this SVG (like probably most of flaticon.com) is not compatible with Vivus. It's `fill` based instead `stroke` based.

**Comment by dfcreative** [comment]
@maxwellito that is what I mean, it does not animate even svgs with only stroked paths. Even the svg from the vivus-instant example with `<style>` removed!
![image](https://cloud.githubusercontent.com/assets/300067/24641394/6be48d80-18cd-11e7-9633-b283191b462c.png)
Is it correct way? I mean can you show example svgs which vivus-instant animates?

**Comment by maxwellito** [comment]
Take a look at these ones: https://github.com/maxwellito/vivus/tree/master/test/manual
