### ISSUE TITLE
Question on functionality

### ISSUE THREAD

**Issue by halofreek45** [maxwellito/vivus#141]
Ok so I am quite new to coding and I am taking a class in school based on learning coding, so I might be extremely ignorant. So I am trying to make a project that draws letters on the screen from pre-made paths using Javascript. At the moment I have a custom svg for every letter and I basically make a clone of that svg depending on what letter I press on the keyboard using id's such as svgA, svgB, svgC, svgD, etc... Is there a way to do this without using an svg per letter? And at the moment even with a custom svg per letter it doesnt seem to work.

var startXPos = 100;
var startYPos = 50;
var drawing = false;
var availableLetters = {
    "A": true,
    "B": true,
    "C": true,
    "D": true,
    "E": true,
    "F": true,
    "G": true,
    "H": true,
    "I": true,
    "J": true,
    "K": true,
    "L": true,
    "M": true,
    "N": true,
    "O": true,
    "P": true,
    "Q": true,
    "R": true,
    "S": true,
    "T": true,
    "U": true,
    "V": true,
    "W": true,
    "X": true,
    "Y": true,
    "Z": true
}

document.addEventListener("click", function() {
    if (drawing == false) {
      console.log("started vivus?")
        drawing = true;
        new Vivus('svgA', {
            duration: 200
        }, function() {
            $(function() {
                jQuery.Color.hook("fill");
            })
        });
        setTimeout(function() {
            drawing = false;
        }, 2000)
    }
});

document.addEventListener("keyup", function(e) {
  if(availableLetters[String.fromCharCode(e.keyCode).toUpperCase()]) {
    var clonedLetter = $('#svg' + String.fromCharCode(e.keyCode).toUpperCase()).clone(true);
    clonedLetter.attr('id', 'current');

    document.body.append(clonedLetter);

    new Vivus('current', {
        duration: 200
    }, function() {
        $(function() {
          console.log("Started new Vivus");
            jQuery.Color.hook("fill");
            $('letterA').toggleClass('path', 1000)
            clonedLetter.attr('id', '')
        })
    });
  }
  else {
    console.log("Letter is not Available")
  }
})

**Comment by maxwellito** [comment]
Hi there,
I try to think about another way of doing what you would like to do, but unfortunately you will have to use one SVG per letter. However, you could hide them all and display the correct one when needed and reset/start the animation, instead of cloning SVGs on the go. 
If you would like some help to debug, it would be nice to put your code on a JSfiddle. It makes it easier to hack and test.
But from what I can see right now, I think the issue might come from the `start` option. By default it's `inViewport`, while in your case `autostart` would be more appropriate.

```js
new Vivus('current', {
  duration: 200,
  start: 'autostart'
}, function() {
  // ...
});
```

**Comment by halofreek45** [comment]
Ok thank you for the help. As I said I am really new to coding and I would love to learn wherever I can. I have a semi-working version. I made the svg's much smaller and I can type out multiple letters and they will animate but there has too be a delay in the typing or else if a letter is still animating the next letter will appear fully and the letter currently being drawn will restart it's drawing. I am still working on it though so any functionality within Vivus that would be useful to my program would be wonderful :) Thanks again!
