### ISSUE TITLE
Vivus hacks does not work to IE 9,10,11

### ISSUE THREAD

**Issue by TIIGRUS** [maxwellito/vivus#142]
**Vivus version**:  v0.4.0

**Browser**:  IE,9,10,11

**This is my function:** 
new Vivus('my-svg', {
                type: 'delayed',
                duration: 200,
                start: 'autostart'
            },function (obj) {
              obj.el.classList.add('finished');
});

**Error in the Console IE:**
"Unable to get the property "add" link, which is not defined or is NULL"

**Code in the Inspector Chrome**
http://joxi.ru/brRDv8KSJ8BKo2

**Source code**
http://joxi.ru/p278VL4soZLGQA

**Comment by maxwellito** [comment]
Hi @TIIGRUS 
Good catch! IE doesn't support `classList` on SVGs (: [canIuse.com](http://caniuse.com/#feat=classlist)). 
In that case I would suggest a `obj.el.className += ' finished';` instead. But I don't have an IE with me right now for a quick test.

```js
new Vivus('my-svg', {
  type: 'delayed',
  duration: 200,
  start: 'autostart'
},function (obj) {
  obj.el.className += ' finished';
});
```

I should update `HACKS.md`.
Thanks for the issue.

**Comment by TIIGRUS** [comment]
The class is not added.
http://joxi.ru/MAj0jMBF4Yd6Zm

**Comment by TIIGRUS** [comment]
No errors, but the class is not added.

**Comment by maxwellito** [comment]
Damn IE!
Can you try something like this: 

```js
obj.el.setAttribute('class', obj.el.className + ' finished');
```

**Comment by TIIGRUS** [comment]
Nice, work in the IE)), but delete my class name, and paste "[object SVGAnimatedString]".))
http://joxi.ru/krDpw9RsEdGQer

**Comment by TIIGRUS** [comment]
I do not know very well javascript, thank you for your help)

**Comment by maxwellito** [comment]
I'm bad at retro-compatibility with deprecated browsers.
That one should make it

```js
obj.el.setAttribute('class', obj.el.getAttribute('class') + ' finished');
```

**Comment by TIIGRUS** [comment]
Wow, it works! Brilliant!Thank you very much for your help. And for your time.

**Comment by maxwellito** [comment]
You're welcome :)
