### ISSUE TITLE
Error in the Chrome

### ISSUE THREAD

**Issue by TIIGRUS** [maxwellito/vivus#143]
**Vivus version**: v0.4.0

**Browser**:  Chrome  55.0.2883.87 m (64-bit)

I have the error for all the svg. Animation work. But what is this error?
**Uncaught TypeError: Cannot use 'in' operator to search for 'animation' in undefined**
http://joxi.ru/82QVv7LSj4XWKA

What have I done wrong?

**Code init**

var card = new Vivus('svg_home_card', {
                    type: 'delayed',
                    duration: 150,
                    start: 'autostart',
                    dashGap: 20,
                    forceRender: false
                },
                function (obj) {
                    obj.el.setAttribute('class', obj.el.getAttribute('class') + ' finished');
                }),
            binnar = new Vivus('svg_home_binnar', {
                type: 'delayed',
                duration: 150,
                start: 'autostart',
                dashGap: 20,
                forceRender: false
            }, function (obj) {
                obj.el.setAttribute('class', obj.el.getAttribute('class') + ' finished');
            }),
            games = new Vivus('svg_home_games', {
                type: 'delayed',
                duration: 150,
                start: 'autostart',
                dashGap: 20,
                forceRender: false
            }, function (obj) {
                obj.el.setAttribute('class', obj.el.getAttribute('class') + ' finished');
            }),
            live = new Vivus('svg_home_live', {
                type: 'delayed',
                duration: 150,
                start: 'autostart',
                dashGap: 20,
                forceRender: false
            }, function (obj) {
                obj.el.setAttribute('class', obj.el.getAttribute('class') + ' finished');
            }),
            casino = new Vivus('svg_home_casino', {
                type: 'delayed',
                duration: 150,
                start: 'autostart',
                dashGap: 20,
                forceRender: false
            }, function (obj) {
                obj.el.setAttribute('class', obj.el.getAttribute('class') + ' finished');
            }),
            lines = new Vivus('svg_lines', {
                type: 'delayed',
                duration: 1000,
                start: 'autostart',
                dashGap: 20,
                forceRender: false
            }, function (obj) {
                obj.el.setAttribute('class', obj.el.getAttribute('class') + ' finished');
            });

**Comment by maxwellito** [comment]
I'm afraid it must be related to another script in your page. I checked the
Vivus codebase, there is no variable (or property) called 'animation'.

**Comment by TIIGRUS** [comment]
I include svg by object.
My code example: <object data="img/home_svg/3.svg" id="svg_home_card" class="svg_home svg_home_card" type="image/svg+xml"></object>

**Comment by TIIGRUS** [comment]
Scripts in the my page: 
<script src="js/jquery.min.js"></script>
    <script src="js/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/vivus.min.js"></script>

**Comment by maxwellito** [comment]
Is it possible to check your page? It won't be easy to debug like that :)

**Comment by TIIGRUS** [comment]
Thank you! Its is my error in the insprector. Extensions in the Chrome make this error. I disabled all extensions and my error missing. This Issue can close)
