### ISSUE TITLE
Hide / don't show before loaded

### ISSUE THREAD

**Issue by torosushi** [maxwellito/vivus#149]
Hi Thank you for the great work.

I am trying to find ways to not show SVG if vivus js not animating. I am talking about before the vivusjs loaded.

I thought something (like standard jquery show() will animate the object and automatically remove display none) so I tried display none but didn't work with vivus. the object remain display none.

Anything built in from vivus that I can use to hide SVG ?

**Comment by maxwellito** [comment]
Hi there,

First, thanks for the kind words :)
About your issues, I'm not entirely sure to get it but here is a solution.

1. Hide the SVG with CSS : `visibility: hidden;`
2. On the options of your Vivus instance, use a callback on the property
`onReady` which will show the SVG. Something like the following:

```js
new Vivus('your-svg', {
  ...
  onReady: function (vivusInstance) {
    vivusInstance.el.style.visibility = 'visible';
  },
  ...
})
```

I hope this helps

**Comment by torosushi** [comment]
Thank you. I tried, but element visibility remain hidden.

code below:
<object id="logobg_line" style="visibility:hidden;" width="400" height="400" type="image/svg+xml" data="../logobg_line.svg"></object>

jQuery( document ).ready(function() {
	var logobg_line_id = document.querySelector('#logobg_line');
	new Vivus('logobg_line', {
    type: 'delayed',
    duration: 100,
    animTimingFunction: Vivus.EASE,
	onReady: function(logobg_line_id){ logobg_line_id.el.style.visibility = 'visible';
		refit(); 
	}
}, f_logobg);
});

**Comment by maxwellito** [comment]
That's strange.. Can you send me a link to check this please?

**Comment by tukano** [comment]
@torosushi I haven't tried that snippet but mine works well with jQuery:

CSS:
`.animate-svg {
visibility:hidden;
}`

JS:
`  new Vivus(myElements[i], {
          duration: 100,
          type: 'delayed',
          animTimingFunction: Vivus.EASE_IN,
          onReady: function () {
                 $('.animate-svg').css('visibility', 'visible');
           },`

**Comment by JekaPolihovic** [comment]
Uncaught ReferenceError: myCallback is not defined

**Comment by maxwellito** [comment]
Because 'myCallback' function is not defined in your case. Remove 'myCallback'
as last parameter of your Vivus call. This callback is optional.

**Comment by xcash** [comment]
> That's strange.. Can you send me a link to check this please?

Sorry if I'm doing the necromancer here.
That doesn't work because the `vivoinstance.el` is the `svg` element and not the `object` element.
In this case we should modify the parent.
Assuming we call the constructor passing `logo` as our element id, something like the following, placed in `onReady` will do the trick in pure js:

```js
onReady: (vivoinstance) => {
  document.getElementById('logo').style.visibility = 'visible';
}
```
