### ISSUE TITLE
Is it possible to animate <line> instead of path?

### ISSUE THREAD

**Issue by nekken** [maxwellito/vivus#150]
I have a svg like this:

`<svg class=" full-height" style="position:absolute; left:0; top:0; width: 100%;">
        <line id="page-line-2-1" x1="10%" y1="0" x2="90%" y2="0" stroke-width="4" stroke="black"/>
        <line id="page-line-2-2" x1="15%" y1="0" x2="10%" y2="11%" stroke-width="2" stroke="black"/>
        <line id="page-line-2-3" x1="90%" y1="0" x2="90%" y2="100%" stroke-width="2" stroke="black"/>
        <line id="page-line-2-4" x1="10%" y1="11%" x2="10%" y2="75%" stroke-width="2" stroke="black"/>
        <line id="page-line-2-5" x1="10%" y1="11%" x2="0%" y2="11%" stroke-width="2" stroke="black"/>
        <line id="page-line-2-6" x1="10%" y1="16%" x2="0%" y2="16%" stroke-width="2" stroke="black"/>
        <line id="page-line-2-7" x1="10%" y1="21%" x2="0%" y2="21%" stroke-width="2" stroke="black"/>
        <line id="page-line-2-8" x1="10%" y1="26%" x2="0%" y2="26%" stroke-width="2" stroke="black"/>
        <line id="page-line-2-9" x1="10%" y1="31%" x2="0%" y2="31%" stroke-width="2" stroke="black"/>
        <line id="page-line-2-10" x1="10%" y1="75%" x2="0%" y2="75%" stroke-width="2" stroke="black"/>
    </svg>`

Would it be possible to use vivus to animate those lines?

thanks in advance!

**Comment by maxwellito** [comment]
I'm afraid not, because your SVG is using percentages so Pathformer cannot convert these lines into paths. I recommend to use pixel values and set a viewBox.

`Pathformer [parseAttr]: a SVG shape got values in percentage. This cannot be transformed into 'path' tags. Please use 'viewBox'`
