### ISSUE TITLE
Using Vivus for md-icon

### ISSUE THREAD

**Issue by stakkit** [maxwellito/vivus#151]
Hello,
Thank you so much for this plugin.
I am using _Angular Material Design_ UI Components in my site and to add an SVG icon I use the [md-icon](https://material.angularjs.org/latest/api/directive/mdIcon) directive:
`<md-icon id="svg" md-svg-icon="social:domain"></md-icon>`

This directive creates the SVG tag inside md-icon:
`<md-icon id="mySvg" md-svg-icon="social:domain">
        <svg xmlns="http://www.w3.org/2000/svg" fit="" height="100%" width="100%" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24" focusable="false"><g id="domain"><path d="M12 7V3H2v18h20V7H12zM6 19H4v-2h2v2zm0-4H4v-2h2v2zm0-4H4V9h2v2zm0-4H4V5h2v2zm4 12H8v-2h2v2zm0-4H8v-2h2v2zm0-4H8V9h2v2zm0-4H8V5h2v2zm10 12h-8v-2h2v-2h-2v-2h2v-2h-2V9h8v10zm-2-8h-2v2h2v-2zm0 4h-2v2h2v-2z"></path></g>
        </svg>
</md-icon>`

I'm not able to add the id to the SVG tag, so I tried to select the svg in this way:
`new Vivus('mySvg svg', {duration: 200});`

but I get this error:

> Error: Vivus [constructor]: "element" parameter is not related to an existing ID

How can I select the children element?

**Comment by maxwellito** [comment]
Hi there,

The first parameter of the constructor must be the SVG ID if you provide a
string, not a CSS selector.
To select the SVG I recommend to use
`document.getElementById('mySvg').children[0]` (or
`document.querySelector('#mySvg svg')` if you can play with something
modern) to select your tag.
So it would look like this: new Vivus(document.querySelector('#mySvg svg'),
{duration: 200});

However, I'm afraid to tell you that your SVG is not stroke based, so Vivus
won't be able to animate it.
Stroke based is an SVG made of lines and not painted areas.

Maybe these link will give you a better understanding:
https://medium.com/bitmatica-lab/svg-line-animation-for-the-uninitiated-5a65d91c6044#.v9f3ayksf
http://valhead.com/2017/03/03/three-illustrator-tricks-for-better-svg-stroke-animations/

I hope this helps :)

2017-03-15 10:17 GMT+00:00 Mustapha <notifications@github.com>:

**Comment by stakkit** [comment]
Thank you so much Max!

**Comment by maxwellito** [comment]
You're welcome! :)

2017-03-15 11:28 GMT+00:00 Mustapha <notifications@github.com>:
