### ISSUE TITLE
Visus script doesn't load on dfp on a spesific size

### ISSUE THREAD

**Issue by cmanimani** [maxwellito/vivus#154]
I have created a set of banner ads using the vivus script in Hype. I am loading the banners in dfp and they work OK except for a specific size 728x90. I did a number of tests to work around the problem but nothing seems to work. Any idea?

Thanks in advance 

[FISIKON_lines_730x90.zip](https://github.com/maxwellito/vivus/files/951643/FISIKON_lines_730x90.zip)

**Comment by maxwellito** [comment]
Hi there,
I just tried your script and it seems working fine for me. I mean the animations where here and smooth.
The only thing I could find problematic is the trigger. By default, Vivus starts the animation when the SVG is in the viewport. But in your case, you might want to start them automatically. If so I would recommend you to set the option `start: 'autostart'`.

```js
// Exemple
new Vivus ('blue', {
  type: 'async', 
  duration: 80,
  start: 'autostart'
}, myCallback);
```

You can see the [list of options](https://github.com/maxwellito/vivus#option-list)

**Comment by cmanimani** [comment]
Thank you that solved the problem! :)

**Comment by maxwellito** [comment]
You're welcome :)
