### ISSUE TITLE
setframeprogress ر

### ISSUE THREAD

**Issue by alimhabib** [maxwellito/vivus#155]
Dear All 

I can use **setframeprogress** successfully to display the audio and SVG at certain frame , but when playing using **play** method it delay 

please u can download the two links 
https://drive.google.com/file/d/0B9eq-nTDQri4d3F1VjU5X01qRDg/view?usp=sharing 

Any advice please

**Comment by maxwellito** [comment]
Hi there, I think you forgot to mention your problem ;-)

**Comment by alimhabib** [comment]
Ho @maxwellito 
I already mentioned using the play method I see delay while with Setframeprogress no delay at all :)

**Comment by maxwellito** [comment]
Can you please provide me a snippet of your code? I'm afraid to not understand correctly what you're trying to do.

**Comment by alimhabib** [comment]
The time in the paths of SVG calculated using 25 frames/sec 
https://drive.google.com/file/d/0B9eq-nTDQri4XzBZRndsR2tSMXM/view?usp=sharing  this a link to sample code

**Comment by maxwellito** [comment]
Thanks for your snippet.
Unfortunately I couldn't find any weird behavior. I think the delay you
mention is due to the 'scenario-start=29' on the first path. When the Vivus
instance starts to play from the start it will display nothing until the
frame 29.

**Comment by alimhabib** [comment]
Hello Maxwellito,

Thanks for your response again!
The issue here is that I want to playback/animate mySVG at 25 fps and it seems that either the browser or the vivus.js library has a default playback/animation fps setting of 60 fps. As a result, the SVG set to 25 fps relevant duration is played back at 60 fps making it play much faster than the audio file!
I was wondering if there was any way to modify the code and playback at any desired fps?

**Comment by maxwellito** [comment]
I see :) the frame rate depends on the browser. At best, it will reach 60fps on Chrome, but if your page is requesting a lot of animations/updates/repaint the frame rate will decrease.

However you can hack the library easily. At the end of `src/vivus.js` there's the fallback code to use `requestAnimationFrame` and `cancelAnimationFrame`. This snippet try to get the original browser function method regarding of the platform or use `setTimeout` if not available.

*src/vivus.js : 720*

```js
/**
 * Alias for `requestAnimationFrame` or
 * `setTimeout` function for deprecated browsers.
 *
 */
requestAnimFrame = (function () {
  return (
    window.requestAnimationFrame       ||
    window.webkitRequestAnimationFrame ||
    window.mozRequestAnimationFrame    ||
    window.oRequestAnimationFrame      ||
    window.msRequestAnimationFrame     ||
    function(/* function */ callback){
      return window.setTimeout(callback, 1000 / 60);
    }
  );
})();

/**
 * Alias for `cancelAnimationFrame` or
 * `cancelTimeout` function for deprecated browsers.
 *
 */
cancelAnimFrame = (function () {
  return (
    window.cancelAnimationFrame       ||
    window.webkitCancelAnimationFrame ||
    window.mozCancelAnimationFrame    ||
    window.oCancelAnimationFrame      ||
    window.msCancelAnimationFrame     ||
    function(id){
      return window.clearTimeout(id);
    }
  );
})();
```

You can update this to :

```js
/**
 * Alias for `requestAnimationFrame` or
 * `setTimeout` function for deprecated browsers.
 *
 */
requestAnimFrame = function(/* function */ callback) {
    return window.setTimeout(callback, 1000 / 30); // Set your fps desired here
};

/**
 * Alias for `cancelAnimationFrame` or
 * `cancelTimeout` function for deprecated browsers.
 *
 */
cancelAnimFrame = function(id){
    return window.clearTimeout(id);
};
```

Anyway, to help you I built a quick [hacked version](https://github.com/maxwellito/vivus/files/971753/vivus_fps_hack.zip) using `Vivus.FPS` property to set the FPS desired. This will apply across Vivus instances.

Just set your frame rate then go


```js
Vivus.FPS = 30;
new Vivus('mySVG', {})
new Vivus('mySecondSVG')
...
```

I hope this will help you :)

**Comment by maxwellito** [comment]
Any luck?

**Comment by alimhabib** [comment]
All works fine now thanks a lot , and sorry for late reply

**Comment by maxwellito** [comment]
No problem :)
