### ISSUE TITLE
Uncaught Error: Cannot set property 'cssText' of undefined

### ISSUE THREAD

**Issue by qmanning** [maxwellito/vivus#157]
**FIXED: 
Error is a CHROME EXTENSION error. Laptop installation of Chrome had additional verbiage that indicated it was an EXTENSION error. Other versions of Chrome just stated the error, without mentioning the EXTENSION issue.

Disabling extensions corrected the issue instantly.**

### Getting a weird JavaScript error in Chrome, when I used a link SVG object rather than an inline SVG. The error doesn't happen in Safari. Still seems to animate, however, even in Chrome.

This problem persists whether I am direct linking, as seen below, or dynamically loading in the .SVG.

However, if the SVG is inline, then the problem goes away.

> jquery.color-2.1.2.js:135 Uncaught TypeError: Cannot set property 'cssText' of undefined
>     at jquery.color-2.1.2.js:135
>     at jquery.color-2.1.2.js:663
> (anonymous)	@	jquery.color-2.1.2.js:135
> (anonymous)	@	jquery.color-2.1.2.js:663
> 

DIV OBJECT:
>  object id="experienceIconSVG" type="image/svg+xml" data="assets/images/rs_experience_icon.svg"

VIVUS CALL:

> var eiAnim = new Vivus("experienceIconSVG", {
> 	type: "oneByOne",
> 	duration: 200,
> 	start: 'autostart',
> 	animTimingFunction: Vivus.EASE
> });

Version: v0.4.0

Browser: Chrome

**Apply VIVUS to <object> SVG file**:

**Comment by maxwellito** [comment]
Hi there,
Can you please provide a jsFeddle of your problem? From the error it doesn't look like this error is triggered from Vivus but from one of your jQuery plugins. At no point this library use a `cssText` property.

**Comment by qmanning** [comment]
Sorry for the delay. So, happy to include both a CodePen & a JSFiddle, however, both don't seem to like playing well with the "object" or with having Vivus load the object dynamically to the div. 

For that purpose, I've also included a link to a private server, just so you can see the issue in Chrome. Apologies for having to go against the grain on that one:

**CodePen - OBJECT doesn't seem to load for some reason**
[https://codepen.io/qmanning/pen/dWwdeo](https://codepen.io/qmanning/pen/dWwdeo)

**JSFiddle - OBJECT doesn't seem to load for some reason**
[https://jsfiddle.net/qmanning/e2Lnq7w5/1/](https://jsfiddle.net/qmanning/e2Lnq7w5/1/)

**Site Example - Where you can see the issue**
[http://deadlastgame.com/svg_test.html](http://deadlastgame.com/svg_test.html)

**Comment by maxwellito** [comment]
Thanks for the detailed update 👍 
Nice job :)
