### ISSUE TITLE
Get animation duration from from duration

### ISSUE THREAD

**Issue by benjamin-derepas** [maxwellito/vivus#160]
### How to retrieve real animation duration ?

Here is my settings : 

**Vivus version**: 0.4.0

**Browser**: Chrome 58

I'm using VivuJs to animate my logo on my personnal website. It works very great, but here is the probleme : 

 I have created a loader element , displaying my logo and a visual text progress .
I would like to retrieve the real duration of the animation, on seconds or ms, but Vivus allow only "frame duration". Is there a way to convert "frame duration" into time ?

Best regards

**Comment by maxwellito** [comment]
Hi there,
Im afraid there's no way to use seconds on Vivus. The library use
'requestAnimationFrame' to guaranty a smooth animation, and the frame
duration will depends on your page performance and user machine.
I can recommend you to use Vivus-instant. It will transform your SVG into
an animated one powered by CSS animation. With this you should have the
duration in seconds (or ms). But Im not sure it will fit your needs.
