### ISSUE TITLE
SVG dont animated

### ISSUE THREAD

**Issue by yamaks** [maxwellito/vivus#163]
Hi!
I can not understand why my svg are displayed, but not animated.

JS:
`var vMetering = new Vivus('sMetering', {type: 'delayed', duration: 150, file: '/wp-content/themes/understrap/img/icons/metering.svg'});
	</script>`

HTML:
`<div id="sMetering"></div>`

SVG:
`<svg height="60" viewBox="0 0 60 60" width="60" xmlns="http://www.w3.org/2000/svg"><title/><path d="M59 2h-7.586L49.707.293c-.39-.39-1.023-.39-1.414 0L46.586 2H1c-.552 0-1 .448-1 1v12c0 .552.448 1 1 1h42c.552 0 1-.448 1-1v-4c0-.552-.448-1-1-1s-1 .448-1 1v3h-4v-1c0-.552-.448-1-1-1s-1 .448-1 1v1h-4v-1c0-.552-.448-1-1-1s-1 .448-1 1v1h-4v-3c0-.552-.448-1-1-1s-1 .448-1 1v3h-4v-1c0-.552-.448-1-1-1s-1 .448-1 1v1h-4v-1c0-.552-.448-1-1-1s-1 .448-1 1v1H8v-3c0-.552-.448-1-1-1s-1 .448-1 1v3H2V4h45c.265 0 .52-.105.707-.293L49 2.414l1.293 1.293c.187.188.442.293.707.293h7v10H47c-.552 0-1 .448-1 1s.448 1 1 1h12c.552 0 1-.448 1-1V3c0-.552-.448-1-1-1m-5 7c0-1.103-.897-2-2-2s-2 .897-2 2 .897 2 2 2 2-.897 2-2M8 50c0 1.103.897 2 2 2s2-.897 2-2-.897-2-2-2-2 .897-2 2m42.707-31.707c-.39-.39-1.023-.39-1.414 0L10 57.586 2.414 50 12 40.414l1.293 1.293c.195.195.45.293.707.293.256 0 .512-.098.707-.293.39-.39.39-1.023 0-1.414L13.414 39 16 36.414l1.293 1.293c.195.195.45.293.707.293.256 0 .512-.098.707-.293.39-.39.39-1.023 0-1.414L17.414 35 20 32.414l3.293 3.293c.195.195.45.293.707.293.256 0 .512-.098.707-.293.39-.39.39-1.023 0-1.414L21.414 31 24 28.414l1.293 1.293c.195.195.45.293.707.293.256 0 .512-.098.707-.293.39-.39.39-1.023 0-1.414L25.414 27 28 24.414l1.293 1.293c.195.195.45.293.707.293.256 0 .512-.098.707-.293.39-.39.39-1.023 0-1.414L29.414 23 32 20.414l3.293 3.293c.39.39 1.023.39 1.414 0 .39-.39.39-1.023 0-1.414l-4-4c-.39-.39-1.023-.39-1.414 0l-31 31c-.39.39-.39 1.023 0 1.414l9 9c.195.195.45.293.707.293.256 0 .512-.098.707-.293l40-40c.39-.39.39-1.023 0-1.414M60 45v12c0 .552-.448 1-1 1H17c-.552 0-1-.448-1-1s.448-1 1-1h41V46h-4v3c0 .552-.448 1-1 1s-1-.448-1-1v-3h-4v1c0 .552-.448 1-1 1s-1-.448-1-1v-1h-4v1c0 .552-.448 1-1 1s-1-.448-1-1v-1h-4v3c0 .552-.448 1-1 1s-1-.448-1-1v-3h-4v1c0 .552-.448 1-1 1s-1-.448-1-1v-2c0-.552.448-1 1-1h30c.552 0 1 .448 1 1" fill="#fff" fill-rule="evenodd"/></svg>`

Thanks for help!

**Comment by maxwellito** [comment]
Hi there,
Your SVG is fill based instead of stroke based. Vivus make animation
strokes, not fill areas.
I recommend you this thread https://github.com/maxwellito/vivus/issues/140
, and Vivus instant (: https://maxwellito.github.io/vivus-instant/ ) to
check the compatibility of your SVG.
I'm sorry about that :-/

**Comment by yamaks** [comment]
I will have to remake svg. But vivus is gorgeous!
