### ISSUE TITLE
How to animate sing path in svg file

### ISSUE THREAD

**Issue by Artkoch** [maxwellito/vivus#166]
I'm trying to animate a path and a polygon wrapped into `<g id="g3">`

I call the usual way `new Vivus('g3', {duration: 80});`
But React throws an error saying `Error: Vivus [constructor]: "element" parameter is not valid (or miss the "file" attribute)`
This is because Vivus expects id of the whole svg file. 

Is there, a way animate only the selected item in svg?

**Comment by maxwellito** [comment]
It's now updated :)
