### ISSUE TITLE
Vivus will not initialize on DOM elements added by Ajax or HTML interpolation (Vue.js)

### ISSUE THREAD

**Issue by docmars** [maxwellito/vivus#167]
### Please define your problem or issue as clear as possible.

I am using Vue.js with Vivus in my case. Vue has a handy way of passing a direct DOM node reference of a component around for use with libraries like this through `this.$el`.

In my `mounted()` hook (the equivalent of `element.onload` or `jQuery.ready()`), I am initializing Vivus after requesting an SVG template through `fetch` and assigning the response string to a data variable on the Vue component. Using `v-html` in my component template, I am assigning that component's `innerHTML` to be the resulting SVG string. The SVG displays just fine.

I'm also making sure to make the call to Vivus _after_ the template is fetched and added to the DOM, so this isn't a race condition issue.

Vivus fails to see that the DOM node is an element, even though I'm logging the node prior to making the Vivus call in the CodePen.
```javascript
console.log(this.$el) // --> <div id="#my-svg-root"><svg>...</svg></div>
new Vivus(this.$el, { duration: 60 })
```
Results in:
```
Error: Vivus [constructor]: "element" parameter is not valid (or miss the "file" attribute)
```

**Vivus version**:
0.4.2

**Browser**:
Chrome 60.0.3112.90 (Official Build) (64-bit)

**Steps to reproduce it**:
1. Import (webpack) or fetch an SVG and inline its string result into an HTML element through `innerHTML` or with `v-html` in Vue.js.
2. After this is done, call Vivus on the parent element.
3. The element passed in is not recognized.

**Other considerations**
- I tried passing an ID to Vivus of the parent component's root element, which wasn't recognized as a node either, despite already being mounted and `ready` on the DOM. It's a mystery. :(

**JSFiddle link (or similar platform)**:
https://codepen.io/andymerskin/pen/00eca5c1836b5ff43c2db2aa1981b5db/

Any help would be appreciated. I've tried every approach I could think of at this point. :/ Vivus is amazing and I'd love to use it!

**Comment by maxwellito** [comment]
Hi Andy,

Before all, thank you very much for taking the time to fill an issue correctly. I really like the way you introduced your approach with the different alternatives. It's so useful and pleasant, and I wish everybody was like you. 👍 

I played with your codepen and managed to make work. Vivus constructor only takes the ID of a DOM element or the DOM element itself. Not the parent of the SVG.

As you mentioned the `this.$el` is `<div><svg></svg></div>` which is not valid for Vivus. But you can pass the first child and the magic will happen : `this.$el.childNodes[0]`.

`new Vivus(this.$el.childNodes[0], { duration: 60 })`

I hope this will be helpful

Max

PS: You found a nice workaround to bypass CORS ;-)

**Comment by docmars** [comment]
@maxwellito 

Thanks for the swift reply. I'm glad I could make dissecting this a little easier for you!

I thought for sure I tried a similar approach in Vue, but I must have missed grabbing the child element. (DOM operations are discouraged in Vue wherever possible, but in this case it's unavoidable).

Thanks for the simple fix. I'll give that shot in my larger project next week and see how it goes.

I appreciate your help!

On CORS: Yeah, it's weird. CodePen allows CORS for including assets in your project, so I was surprised the `file` option didn't take, though that's just passing the URL to an `<object>`'s data attribute I'm assuming, so that's probably why.

It would be kind of nice to see Vivus support making an AJAX request for instances where using an object element isn't ideal. But fetch and other libs make it painless anyway, so ¯\_(ツ)_/¯

**Comment by maxwellito** [comment]
:-)

Its pretty cool you sent this issue at this moment because Im rebuilding
triangulart in vue.js, just to discover it. It would be interesting to see
if the framework provide an option to avoid DOM checking on this component
to improve performances.

I will properly consider doing an AJAX request to load the SVG but I will
have security concerns to check. But I would love to implement it only with
'fetch' and not all these old APIs (actually it shouldn't be a problem).

Thanks again for your issue. You have no idea how pleasant it was :-) Do
not hesitate to ask for help!
