### ISSUE TITLE
ViVus Animation not working

### ISSUE THREAD

**Issue by dagenius007** [maxwellito/vivus#173]
I followed the documentation carefully. I dont know what am not getting right
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>joshuaoluikpe</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vivus/0.4.2/vivus.js"></script>
  </head>
  <body style="background-color:#a3016e">
          <object type="image/svg+xml" data="assets/josh.svg" id="josh">			
        <img src="assets/josh.png" height="400">
      </object>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/vivus/0.4.2/vivus.js"></script>

          <script type="text/javascript" charset="utf-8">
            var vivus = new Vivus('josh', {
              duration: 3000,
              type: 'oneByOne',
              animTimingFunction: Vivus.EASE,
              start: 'inViewport'
            },
              function (argument) { }
            );
          </script> 
  </body>

</html>

![captu](https://user-images.githubusercontent.com/16763826/30517496-7b7612c8-9b59-11e7-9898-36398c928863.PNG)

**Comment by maxwellito** [comment]
I can't really know from what you posted.

First, try if your SVG is compatible by testing it with [vivus-instant](https://maxwellito.github.io/vivus-instant/). Your SVG must be stroke based. If no animation is happening. your SVG is not stroke based.

Second point, what's happening in your case? Do you get en error? The SVG is displayed but no animation is triggered?

**Comment by dagenius007** [comment]
Using the vivius-instant ,my svg does not animate.
Secondly I get no error

**Comment by maxwellito** [comment]
I'm afraid your SVG doesn't seems compatible with Vivus. This library can only animate stroke based SVGs, it's a requirement, all the animation is based on it.
