### ISSUE TITLE
How to stagger multiple SVG start times

### ISSUE THREAD

**Issue by dlewand691** [maxwellito/vivus#179]
Hello! This isn't really an issue but more of a how-to question. 

I have 3 SVGs on the page that I'm animating. Instead of them all starting at the same time, I'd like them to play one after another with a slight delay between each. 

I've tried a few variations but can't seem to get it to work. Is this possible?

Here is a codepen project for example:
[https://codepen.io/danlewski/project/full/ZLEeVy/](https://codepen.io/danlewski/project/full/ZLEeVy/)

**Comment by Showcase-Joz** [comment]
Last I used vivus there was a delay attribute. Alternatively you could have a js callback run when first event finishes ;)

**Comment by Showcase-Joz** [comment]
... Furthermore I think the vivus examples run in succession. So you could use Dev tools to check how that's happening.

**Comment by maxwellito** [comment]
Sorry Im doing this from holidays, from my phone.

I recommend you the following: create the 3 instances to load the SVG, then
start the breaker when in the viewport. When finiahed it will start the
chip, then the server. I hope it works.

// Create your instances
var beaker = new Vivus('beaker', {
  duration: 100,
  type: 'oneByOne',
  start: 'inViewport'
}, function(){
  // When Breaker finish, start the chip
  chip.play();
});

var chip = new Vivus('chip', {
  duration: 100,
  type: 'oneByOne',
  start: 'manual' // Start manually from the previous callback
}, function(){
  // When chip is finished, start server
  server.play();
});

var server = new Vivus('server', {
  duration: 100,
  type: 'oneByOne',
  start: 'manual' // Start manually from the previous callback
}, function(){});

**Comment by dlewand691** [comment]
Thanks, maxwellito. That worked perfectly! Very much appreciated.
