### ISSUE TITLE
endless

### ISSUE THREAD

**Issue by Spica2** [maxwellito/vivus#18]
is there no callback on reverse animation?
Put this as a callback
					switch (tick) {
						case 0:
							tick=1;
							hi.reset().play();
							break;
						case 1:
							tick=0;
							hi.play(-1);
							break;
						}
But the reverse animation does just come up once. how to make it infinite?

**Comment by maxwellito** [comment]
Now the callback function is called at the end of each animation. And to know if the instance is at the start or end, just check the property `currentFrame` (Equal to 0: start, else: end).
