### ISSUE TITLE
Vivus doesn't animate rounded rectangle borders.

### ISSUE THREAD

**Issue by codebymikey** [maxwellito/vivus#180]
Hi @maxwellito 

**Vivus version**: 0.4.2

**Browser**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Steps to reproduce it**:

- Open the fiddle
- There's two svgs in there, the original on the left, and the other animated by Vivus.

**JSFiddle link (or similar platform)**:
https://jsfiddle.net/Lve1ousu/

The issue is that the `Pathformer.prototype.rectToPath` doesn't read the `rx` and `ry` values and translate them into the paths. I tried my hands at it, but i'm not very versed with the svg format.

I think this [could](http://www.remy-mellet.com/blog/179-draw-rectangle-with-123-or-4-rounded-corner/) potentially be of use.

**Comment by codebymikey** [comment]
Made some progress on this, roughly based off [this inkscape code](https://github.com/wdv4758h/inkscape/blob/master/share/extensions/pathmodifier.py):
```javascript
Pathformer.prototype.rectToPath = function (element) {
  var newElement = {},
      x      = parseFloat(element.x)      || 0,
      y      = parseFloat(element.y)      || 0,
      width  = parseFloat(element.width)  || 0,
      height = parseFloat(element.height) || 0;

  var rx = parseFloat(element.rx) || 0,
      ry = parseFloat(element.ry) || 0;

  if(rx !== 0 || ry !== 0) {
      // Try and render the border radius
      newElement.d = 'M ' + (x + rx) + ',' + y + ' ';
      newElement.d += 'L ' + (x + width - rx) + ',' + y + ' ';
      newElement.d += 'A ' + rx + ',' + ry + ',0,0,1,' + (x + width) + ',' + (y + ry) + ' ';
      newElement.d += 'L ' + (x + width) + ',' + (y + height - ry) + ' ';
      newElement.d += 'A ' + rx + ',' + ry + ',0,0,1,' + (x + width - rx) + ',' + (y + height) + ' ';
      newElement.d += 'L ' + (x + rx) + ',' + (y + height) + ' ';
      newElement.d += 'A ' + rx + ',' + ry + ',0,0,1,' + x + ',' + (y + height - ry) + ' ';
      newElement.d += 'L ' + x + ',' + (y + ry) + ' ';
      newElement.d += 'A ' + rx + ',' + ry + ',0,0,1,' + (x + rx) + ',' + y;
  } else {
      // Keep existing behaviour
      newElement.d  = 'M' + x + ' ' + y + ' ';
      newElement.d += 'L' + (x + width) + ' ' + y + ' ';
      newElement.d += 'L' + (x + width) + ' ' + (y + height) + ' ';
      newElement.d += 'L' + x + ' ' + (y + height) + ' Z';
  }
  return newElement;
};
```

The code seems to work for this simple shape, but doesn't work properly on one of my svgs.

**Comment by maxwellito** [comment]
👍 

I think I was wondering the same thing but forgot about it. This is pretty important! Thanks for providing help and details. I'll try to implement and release it this weekend.

Many many thanks!

**Comment by codebymikey** [comment]
Thanks for putting in the fix!
