### ISSUE TITLE
Animate SVG which has been set as background

### ISSUE THREAD

**Issue by michel-janssen** [maxwellito/vivus#182]
I want to use Vivus.js for animating a SVG which has been set as a background-image in CSS. I created the SVG with **Vivus instant**, but it triggers immediately when the page is loaded. Is it possible to do such thing? Maybe not with Vivus instant, but using custom code..

Or will the only solution be, to drop the background image and work with **Inline SVG** or **Dynamic load** by an object.

**Comment by maxwellito** [comment]
Im afraid you will have to use the inline SVG. Repass your SVG on Vivus
Instant and set the setting for manual start. Play with CSS to make it look
as background. Then when you need to play it, add the trigger class to your
SVG.
