### ISSUE TITLE
reverse animation start from end 

### ISSUE THREAD

**Issue by rafaelmagalhaes** [maxwellito/vivus#184]
Hi great plugin, really like it,

I am having an issue with an SVG and i need some help,
I would like the animation to start from end, to start, instead of start line to end line
heres a jsfiddle with the svg  

https://jsfiddle.net/41L4nej5/31/

Is it possible to do this with the vivus or would  i have to change the SVG paths ?

**Comment by maxwellito** [comment]
Thanks for providing the jsFiddle, it makes it all clear now :) but Im
afraid there's no options to ask vivus to draw a path backward. You will
have to redraw your SVG, sorry about that.

**Comment by rafaelmagalhaes** [comment]
Hi thanks for replying  i managed to do with CSS
All I had to do was to use CSS to flip the SVG path :) 

`
path {
  -moz-transform: scaleX(-1);
  -o-transform: scaleX(-1);
  -webkit-transform: scaleX(-1);
  transform: scaleX(-1);
  filter: FlipH;
  -ms-filter: "FlipH";
  transform-origin: 50% 50%;
}
`

here's the updated fiddle hope it can help someone else 

https://jsfiddle.net/41L4nej5/36/
