### ISSUE TITLE
Kills all JS if not all ID's are available in document

### ISSUE THREAD

**Issue by lionnez** [maxwellito/vivus#185]
Hello! First of all: I love vivus.js, thank you. I'm new to JS, and I ran into a problem with the setup. vivus.js is part of my global script.min.js. when all ID's are available in the html document, everything works great. but when only a single ID that is requested by the instance is missing, or if none are available, it kills all javascript on the website. what am I missing? thank you very much.

Vivus Version: v0.4.2
Safari Browser: 11.0

index.html
(no ID, kills all js)

```
<body>
    <div>
        Content
    </div>
<script src="/js/script.min.js"></script>
</body>
```

example.html
(not all IDs, kills all js)

```
<body>
    <div>
        <svg id="mysvg1">
        </svg>
    </div>
<script src="/js/script.min.js"></script>
</body>
```

example2.html
(all IDs, all js works)

```
<body>
    <div>
        <svg id="mysvg1">
        </svg>
    <div>
    </div>
        <svg id="mysvg2">
        </svg>
    </div>
<script src="/js/script.min.js"></script>
</body>
```

Set up

```
new Vivus('mysvg1', {duration: 200}, myCallback);
new Vivus('mysvg2', {duration: 200}, myCallback);
```

**Comment by maxwellito** [comment]
Hi there,

Thanks for these kind words :)
I think the problem is the following: Providing an invalid ID to the Vivus
constructor will throw an error and might stop your script (depending how
it's build). There's no option to disable it. I would recomend you to wrap
this in a try-catch, or make sure the IDs are available before creating
your Vivus objects.

I hope this will help you.

**Comment by lionnez** [comment]
Thank you for your answer. I tried wrapping it with something like this

```
if (typeof Pathformer == 'function') { 
  Pathformer(); 
}
```

but I don't really know what I'm doing. And since I'm using global JavaScript and a lot of sites, some of them with vivus elements and some of them without, I can't use vivus until I'm better at js. Because it needs to work regardless of how many ID's are in the current document.

Thank you anyway and I hope to be more capable soon.

**Comment by maxwellito** [comment]
I must admit, I really don't understand what you're trying to do with your
"if". Is it because of an error message you get in your web console?

**Comment by lionnez** [comment]
sorry, I don't know how else to explain it.

when I get this error:

```
[Error] Error: Vivus [constructor]: "element" parameter is not related to an existing ID
	setElement (script.min.js:451:151)
	h (script.min.js:445)
	Global Code (script.min.js:466:151)
```

all my other javascript in my global script.min.js does not work.

I only get this error when **one, or more, or all** ID(s) is missing. I dont use all ID's on all sites.

what I tried to do is tell the vivus.js to work, when any ID is available, no matter how many are missing.

**Comment by maxwellito** [comment]
Sorry about the delay. 
Did you managed to fix the issue with the `try ... catch ...`?
If not, post your code where I can see it. I'll try to help you :)

**Comment by lionnez** [comment]
No worries! I did try "try and catch" but it didn't work and it also wasn't clean enough. I ended up deactivating vivus for now. I don't have code other than your original library and a separate JS with the instances. as I said, I'm not good enough with JS. all I try to do is not getting an error when an ID is missing.

maybe this works, I will try it

`document.getElementById('example')!=null`

or

`if(document.getElementById('example')!=undefined) hide('example');`

thanks for your help.

**Comment by maxwellito** [comment]
As I said before, if the ID doesn't exist, it will trigger an error.

So for each of your instances I would suggest you to test is the ID is available before running the code.

```js
if (document.getElementById('mysvg1')) {
  new Vivus('mysvg1', {duration: 200}, myCallback);
}
if (document.getElementById('mysvg2')) {
  new Vivus('mysvg2', {duration: 200}, myCallback);
}
```

Also, make sure that `myCallback` exists if you plan to use it.

**Comment by lionnez** [comment]
it works!!!! thank you so much! I really need to step up my js game! thank you! now I can use vivus again :)

**Comment by maxwellito** [comment]
All güüd then :)
