### ISSUE TITLE
IE animation is slow 

### ISSUE THREAD

**Issue by rehamwael** [maxwellito/vivus#189]
IE animations is so slow in IE

    new Vivus('smart-solutions-svg',
        {
            type: 'delayed',
            duration: 200,
            pathTimingFunction: Vivus.EASE_OUT,
            animTimingFunction: Vivus.EASE,
	   forceRender : true
        });

**Comment by maxwellito** [comment]
The "force rendering" is something extremely heavy in terms of resources.
So if your SVG is complex it will have an important impact on your
performances.

https://github.com/maxwellito/vivus/blob/master/readme.md#internet-explorer
