### ISSUE TITLE
Ease out path before full animation completed

### ISSUE THREAD

**Issue by fntcstudios** [maxwellito/vivus#190]
Many thanks for a very handy plugin which works like a charm. I've tried finding a solution for the following but haven't, my apologies if this has already been answered. 

Now, is there a way of letting independent path(s) ease/fade out before the whole animation is completed? Something like EASE_OUT after the data-duration in scenario mode, but from a time based mode/duration (ie; after 500, ease_out)? So the paths can act independent rather than operated as a whole (svg object).

**Vivus version**: 0.4.2

**Comment by maxwellito** [comment]
Hi there,
You've been looking at the right thing : scenario mode. But it looks like it doesn't solve your problem. If you plan to draw back (or fade) a path before the end of the animation, Vivus got nothing built in to help you. You will have to hack Vivus. 
If you provide a jsFiddle I can try to help you.
