### ISSUE TITLE
Feedback "start" and "end" events for each path

### ISSUE THREAD

**Issue by ShakurOo** [maxwellito/vivus#192]
Does it possible to know when a animation path starting and ending for _scenario_ case?

I would like add some specifics classes in each `<path>` of the SVG depending on its animation state. Theses classes allows me to fills the `<path>` with slowly transition. And i want do it each end of `<path>` animation.

For the moment, the only async way than i found is adding classes inside a encapsulation of multiple `setTimeout()` but the result is different each time according network quality and hardware perfomance...

Each render product more or less lags ...

**Comment by maxwellito** [comment]
I'm afraid Vivus doesn't provide any events related to the progress of paths. 

However I took the challenge and tried to hack a little bit without touching the library. Here is what you can do.

```js

// Create your Vivus object
new anim = new Vivus('mySVG', ...);

// Go through the mapping of the Vivus instance
// and hook the `progress` property of every path
// object. When the value 1 will be set (: progress complete)
// it will call a function to let you do your magic.
// This snippet must be right after the instance creation
anim.map.forEach(function (pathObj) {
  var progress = 0;

  Object.defineProperty(pathObj, 'progress', {
    get: function () {
      return progress
    },
    set: function (v) {
      if (v === 1) callbackMagic(this)
      progress = v
    }
  })
})

// Here is the function that will be called when a path is complete.
// Feel free to hack it and do your stuff ;-)
function callbackMagic (pathObj) {
  // Do your magic here
  // 
  // pathObj is an object containing few info
  // pathObj.el : Path DOM element
  // pathObj.length : line length
  // pathObj.duration : animation duration in frames
  // pathObj.startAt : animation start point
  console.log(pathObj)
}
```
