### ISSUE TITLE
Attempting to use class selector with child element

### ISSUE THREAD

**Issue by jasonday** [maxwellito/vivus#193]
I've tried several iterations of the answer to issue #78 , but I continue to run into the same error:
`Uncaught Error: Vivus [constructor]: "element" parameter is not valid (or miss the "file" attribute)`

My construction is below. I have several `svg` elements contained in containers with class of `.portfolio-svg`. I'm looping through each instance of `.portfolio-svg` and then querying for the `svg` child element to run the vivus instance. Live example: https://dayjason.com

```
var myCallback = function () {};

// Get your HTMLCollection of SVG to animate
var mySVG = document.querySelectorAll(".portfolio-svg");

// Go across them to create a Vivus instance
// with each of them
for (var i = mySVG.length - 1; i >= 0; i--) {
  var svg = mySVG[i].querySelectorAll('svg');
  new Vivus(svg, {duration: 3000, }, myCallback);
}
});
```

**Comment by maxwellito** [comment]
The Vivus constructor accepts a SVG DOM element. While `querySelectorAll` return a NodeList object. 

The following should do the trick.

```js
var myCallback = function () {};

// Get your HTMLCollection of SVG to animate
var mySVGs = document.querySelectorAll(".portfolio-svg svg");

// Go across them to create a Vivus instance
// with each of them
for (var i = mySVGs.length - 1; i >= 0; i--) {
  new Vivus(mySVGs[i], {duration: 3000, }, myCallback);
}
```

**Comment by jasonday** [comment]
ah! thanks. Works perfect.
