### ISSUE TITLE
Object loaded does not contain any SVG at HTMLObjectElement.onLoad

### ISSUE THREAD

**Issue by FabianEllenberger** [maxwellito/vivus#194]
Hi there,

first of all, thanks for this awesome library!
Vivus is working like a charm with local files, but I'm trying to load a file from a server like the following:

```javascript
<div id="my-svg"></div>

new Vivus('my-svg', {
  duration: 200,
  type: 'oneByOne',
  file: image.sizes.medium,
  animTimingFunction: Vivus.EASE
})
```

while `file: image.sizes.medium` equals `https://my-url.file.svg` for example.
The file gets displayed on the website and also in the DOM, an it is a SVG.
Somehow Vivus tries to create the instance before it is actually loaded i assume.

Is there a known way to achieve this or is it not possible at the moment?

Thanks! 🙏🏻

**Comment by maxwellito** [comment]
Hi there :)

Do you get any errors from the console? I suspect the problem to be due to
cross-origin issues.

**Comment by FabianEllenberger** [comment]
@maxwellito 

Thanks, i'll check it out! 

But, the thing is if i take the same file and load it locally from a normal folder it works just fine, so i think the file should be valid :-/ (also works in the nice Vivus Instant when i drop it there)

**Comment by patternuser** [comment]
You need to use an <object> in your markup, not a div for the ID vivus uses.

**Comment by millsoft** [comment]
I just got the same problem but when I open the page like this: `file:///user/mike/blah.html` if I open the page on a server, eg `http://localhost/blah.html` it works.
