### ISSUE TITLE
Is it possible to force .play() behavior if SVG is not entirely within viewport? 

### ISSUE THREAD

**Issue by willdelphia** [maxwellito/vivus#195]
Hi I am attempting to use vivus to reveal some SVGs on a page. 

The problem seems to be that my svgs are not entirely on the page viewport... for design reasons they live on the edges of the page and overflow into the off-screen space. In addition they are rotated with a CSS transform on their containing div. (Not sure this last part is relevant , but it explains the following image) 

![screen shot 2018-05-31 at 12 39 58 pm](https://user-images.githubusercontent.com/4534359/40798235-248d4148-64d0-11e8-8e93-d27d56fdda2f.png)

Everything is okay in safari and firefox, but in chrome they do not execute  the VIvus effect. 

With a little googling I have come to suspect that the issue is that Vivus doens't start play until an svg is entirely visible within the window. So my question is, is there any way to bypass this functionality and just play the thing even though certain edges of the svgs are not visible to the user? 

Thanks, 
Will

**Comment by maxwellito** [comment]
Hi Will,

You are completely right. Unfortunately, Vivus doesn't accept a percentage of visibility to trigger the animation, it waits to be completely visible. However I have 2 options for you.

1. Trigger the animation when you feel it's right by using `.play()`
2. Proxying [`Vivus.prototype.isInViewport`](https://github.com/maxwellito/vivus/blob/master/src/vivus.js#L668) to define when the animation is good to start. By default it's 1, but you can try with the following :

```js
Vivus.prototype.isInViewportProxy = Vivus.prototype.isInViewport;
Vivus.prototype.isInViewport = function (el) {
  return this.isInViewportProxy(el, .5) // Please try with different values than .5
}
```

I should definitely make more tests about that and offer it as an option for Vivus constructor.
I hope this helps.
