### ISSUE TITLE
Set "setFrameProgress" by scroll position ends in piecewise animation? 

### ISSUE THREAD

**Issue by mittererr** [maxwellito/vivus#196]
If setFrameProgress ist set by scroll position, the animation ends in an awful piecewise animation.

The progress variable seems to be OK (watched by console.log).

How to get this animation smoother?

```
$(".fullwidth-facts").each(function(){
    		var vivus = new Vivus(this, {
      		  file: "/wp-content/themes/xyz/img/facts-line.svg",
      		  start: "manual",
      		  onReady: function (vivus) {
      			  vivus.reset();
      			  var svg = $(".fullwidth-facts svg#Ebene_1");
      			  $(".fullwidth-facts svg#Ebene_1").remove();
      			  $( ".fullwidth-facts" ).prepend( svg );
      		  }
      		});

    		var progress = 0;
    		var dh = $(document).height(); // document height
    		var wh = $(window).height(); // window height
    		var eh = $(this).height(); // element height
    		$(window).on("scroll", function(){
    			var eot = $(".fullwidth-facts").offset().top;
    			var wsp = $(window).scrollTop() + wh;
    			if(eot < wsp && wsp < (eot+wh+eh) ) {
    				progress = ((100/(wh+eh)) * (wsp-eot)) / 100;
    				vivus.setFrameProgress(progress);
    			}
		  });
});
```

**Comment by maxwellito** [comment]
Can you please provide a jsFiddle? And also some comments in your code.
Thanks

**Comment by mittererr** [comment]
See [JSFiddle](https://jsfiddle.net/3z0Ls6xj/4/).
The line should be animated from left to right and other way around while scrolling up or down the page.

**Comment by maxwellito** [comment]
I'm afraid to not understand what you're trying to achieve. I get the following, is it not what you expect?

![output](https://user-images.githubusercontent.com/1097232/41157216-d82aaeb4-6b1c-11e8-886b-0b14e27a6d8c.gif)

**Comment by maxwellito** [comment]
I think it's a restriction due to https or cross-domain policy. If you try locally with the SVG hosted on the same domain it should be all good.

**Comment by mittererr** [comment]
Yes, locally it is working but it "jumps". The line does not animate smooth, it jumps in maybe 15px pieces. Is your animation smooth?

**Comment by maxwellito** [comment]
It took me a while, but I got it. Add the property `duration` in your options with a crazy value, something like `duration: 10000000`. 

```js
var vivus = new Vivus(this, {
  start: 'manual',
  duration: 1000000,
  onReady: function (vivus) {
    vivus.reset();
  }
});
```

Let me explain, by default Vivus will set a duration of 200 frames. So when you update the progress, it will find the closest frame on this value. 200 is not enough, 1000000 should give you enough granularity. 

It's now smoooooth :)

**Comment by mittererr** [comment]
That's it - Thank you! Really smooooooth!

**Comment by mittererr** [comment]
One more question: Does the source posted above work in your Chrome ver 67? At my site, the animation is always at 100% in Chrome browser.

**Comment by maxwellito** [comment]
Yes I do now, I think my mistake was to use your SVG inline instead of loading it dynamically. If you think this problem is identical to #198, is it ok to close yours and continue in the other issue? Thanks :)
