### ISSUE TITLE
"setFrameProgress" does not work on Chrome 67.0.3396.79 (Mac)

### ISSUE THREAD

**Issue by mittererr** [maxwellito/vivus#197]
"setFrameProgress" does not work on Chrome 67.0.3396.79. It does in prior version 66. After an update today it stops working.

**Comment by maxwellito** [comment]
I'm afraid the library is fully working on the latest Chrome. I just tried on my machine with the exact version and the behavior is as expected.

1. Go on the [demo page](http://maxwellito.github.io/vivus/)
2. Open the console
3. Stop the intro animation : `hi.stop()`
4. Set a frame progress : `hi.setFrameProgress(.3)`
