### ISSUE TITLE
Console Error - Mixed Content

### ISSUE THREAD

**Issue by mofizul21** [maxwellito/vivus#200]
Hi,

Please see the screenshot- http://prntscr.com/k2or3g is it possible to fix the console error?

**Vivus version**: v0.4.1

**Browser**: Google Chrome Latest

Thanks for your work.

BR,
Mofi

**Comment by maxwellito** [comment]
Hello,

Yes, I think as part of a Vivus callback you are loading this
'hqdefault.jpg' picture. Please make sure the URL is using https. Then your
content won't be mixed anymore.

**Comment by mofizul21** [comment]
Hi,

It was okay before adding SSL. After adding the SSL we're viewing it.

You're saying that "Please make sure the URL is using https. Then your
content won't be mixed anymore." Since we're viewing error after adding SSL/https, then how to we can solve it?

Have another way? Where from we can edit the image URL?

BR,
Mofizul

**Comment by maxwellito** [comment]
In `/test/assets/js/embed/embed.js` line 31. Change the URL protocol to
`https` and the problem should be solved.

**Comment by maxwellito** [comment]
Any updates?

> Just to make sure, 'embed.js' is a file in your website. Its not related
to Vivus.

**Comment by mofizul21** [comment]
Hi MaxWell,

Thanks for your awesome support. You solved my problem.

Thanks again.

Cheers,

*Mofizul I.*
*Professional Web Developer*

*http://themepack.net <http://themepack.net>*
*http://spoilcoconut.com <http://spoilcoconut.com>*
