### ISSUE TITLE
Can't create animations from vivus instant from some weeks

### ISSUE THREAD

**Issue by Tpikas** [maxwellito/vivus#206]
### Please define your problem or issue as clear as possible.

I was playing with vivus online some weeks ago and were fabulous but now I can not get to creat any animation. I've tried many different svg files but never works again for me.

**Vivus version**:
https://maxwellito.github.io/vivus-instant/

**Browser**:
Google Chrome is up to date
Version 69.0.3497.100 (Official Build) (64-bit)

**Steps to reproduce it**:
1. Upload coffe-please.svg (download from here for testing: https://shopcraftables.com/products/coffee-please-free-svg-cut-file/)
2. Nothing happens
3. Anyway exported animated version and nothing happens

I've tried too with a custom svg created from Illustrator and same issue
Thanks in advance!!

**Comment by maxwellito** [comment]
Hi there,

Thanks for reporting a bug with all the information. However it's not a bug (or a feature ;-) it's just how the library works. Vivus make the animations on the border of shapes (aka `strokes`) and not on the fill color. This is also why I mention 'stroke based SVG' on the intro.
I used the SVG you provided, changed the line 5 from `<g>`  to `<g fill="none" stroke="black" >`. You will see the visual aspect of the design is different. But this one Vivus can animate it.

I hope this was helpful :)

**Comment by maxwellito** [comment]
Hey @ricmann I might need more details. I didn't detected any issues recently, except the big issue on [Chrome recently](https://github.com/maxwellito/vivus/issues/198) but it got fixed since.

**Comment by ricmann** [comment]
Hi again :)

I can't get to the bottom of it. When I create a Vivus animation on my PC, which is my workhorse, it fails. When I produce one on my Surface Book it works perfectly!!

Doesn't dint my enthusiasm for Vivus however :)
