### ISSUE TITLE
Show element after vivus animation stops

### ISSUE THREAD

**Issue by FiddlePlus** [maxwellito/vivus#207]
Hey!

It's not really an issue with the vivus; more like the request of guidance.

I want to show a hidden element (img, for example, or div) after vivus is done playing. Is it possible?

I'm not trying to waste anyone's time and I'm fairly new to js, so don't be too harsh on me ;)

**Comment by maxwellito** [comment]
Hey there,

Don't worry about being a beginner :)
The third argument of the Vivus constructor is the callback for when the
animation is finished. This where you can show/hide your elements.

new Vivus('your-div', {/* your-options */}, function () {
  // Everything here will be called when
  // the animation finishes
  document.getElementById('hello').style.display = 'none'
});

This should do the trick :)
