### ISSUE TITLE
effect for svg animation

### ISSUE THREAD

**Issue by teamhide** [maxwellito/vivus#208]
**Vivus version**: 0.4.4

**Browser**: Chrome

I'm new at not only svg animation but also vivus.js

I want to know that is there any method for below effect?

1. Opacity

2. Light effect

3. Change color

4. Gradient

5. Blur

I searched in google, but any result can found.

Can I apply it with vivus.js? Or have to modify svg?

Thanks.

**Comment by maxwellito** [comment]
Hi there,

I'm afraid Vivus is built for SVG drawing animation only. No methods will
help with one of the listed effect. You might try and use a different
library for that. Maybe anime.js will help you in your quest :)
