### ISSUE TITLE
Grammar and typos

### ISSUE THREAD

**Issue by frankiekie** [maxwellito/vivus#209]
### Please define your problem or issue as clear as possible.
I just was looking through the documentation in the Vivus source file and noticed some typos/incorrect spelling. Was wondering if there was any interest in having someone go through documentation with a fine toothed comb to weed out any of those typo/spelling errors?
For a problem, please fill the following:

**Vivus version**: Current

**Browser**: All

**Steps to reproduce it**: Open Source JS files

**JSFiddle link (or similar platform)**:
*No personal website will be allowed, only sandboxed platform where the code is isolated, clear and can be hacked. I don't want to debug uglified code between 42 libraries.*

*[note]*
Please have a minimum of politeness. There's unfortunately only me as contributor/maintainer which help on my free time, I'm not the Amazon customer service or your Mom. I don't ask to send me flowers and tell me how amazing Vivus is (that won't make me help you quicker). But please try to do as much as you can before opening an issue: check that no closed issue mention a similar problem, that your script is executed correctly (conflicts, race conditions...).. Thanks :)
*[/note]*

**Comment by maxwellito** [comment]
Hi Connor,

Thanks for asking and offering. PRs about grammar and typos are always
welcome. English is not my mother tongue :) I guess you wanted to review
the comments before method definitions, right?

**Comment by connor-wilson-dev** [comment]
I haven't forgotten about this, I just haven't had any time to be able to go over all the comments in this. Mainly in src/vivus.js I noticed some spelling/grammar mistakes, but I figure while I'm in there I may as well check out everything else. I've already got my own fork going, but I hope this saturday I will have some time to take another look at everything
