### ISSUE TITLE
[QUESTION] Where I can find the CI service? 

### ISSUE THREAD

**Issue by gustavosizilio** [maxwellito/vivus#212]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by maxwellito** [comment]
Nope, never. I maintain the repo so I'm making sure the tests pass during PR and before releases. 

However I've never setup myself the CI system, I'm gonna have a look at this.

**Comment by maxwellito** [comment]
**UPDATE**: Now yes!

Check #214 for more info.
The CI use Travis: here is [the config file](https://github.com/maxwellito/vivus/blob/master/.travis.yml)
