### ISSUE TITLE
restart animation on click, its possible?

### ISSUE THREAD

**Issue by marcelomgerais** [maxwellito/vivus#216]
hi. nice script. tks a lot. 
its not a issue. its a question:
its possible to restart the animation on mouse over or click?
if i click on image/svg it can be restart the animation. is possible?
and other case: if i use long landpage, when target the element/section it starts. 
its possible?
tks, marcelo

**Comment by maxwellito** [comment]
Hallo Marcelo,

Yes, it's possible, this is what's happening on the [demo page](http://maxwellito.github.io/vivus/). The top logo (: Hi there) and the 3 shutters can be restarted on click. 

Here is how you can do it: 

```js
// Init your Vivus instance (with your own settings, this is just an example)
var myVivus = new Vivus('the-container-id', {type: 'delayed', duration: 150}),

// Then listen to the event of your choice to restart the animation
myVivus.parentEl.addEventListener('click', function () {
  myVivus.reset().play();
})
```

I hope this helps :)

**Comment by marcelomgerais** [comment]
hi max, i will try it. 
im using script on my landing page [(.](<script `src="js/vivus.min.js"></script>)`  and calling the svg's from
code like this: `<object type="image/svg+xml" class="img-responsive ico-box" data="svg/ico-coop.svg"></object>`;
i need to insert your code in another script on this same page?
tks for response.
cheers!

**Comment by maxwellito** [comment]
You need to use it where you start running Vivus. So far to make the
animation working you must use 'new Vivus(...)' somewhere in your code,
right?

**Comment by marcelomgerais** [comment]
i will try... im not a programmer... im a designer... html + css. 
i put this code on page:
' <script type="text/javascript">
// Init your Vivus instance (with your own settings, this is just an example)
var myVivus = new Vivus('coop', {type: 'delayed', duration: 150}),


// Then listen to the event of your choice to restart the animation
myVivus.parentEl.addEventListener('click', function () {
  myVivus.reset().play();
})
</script>'
and the line of the svg is:
' <object id="coop" type="image/svg+xml" class="img-responsive ico-box" data="svg/ico-coop-colab_branco-animated.svg"></object>'
but it does not works. i will try later.
tks a lot, max!

**Comment by maxwellito** [comment]
Yes, it should be.

In your HTML file the order should be like this:


1. Include the library: <script src="js/vivus.min.js"></script>

2. Your SVG with the 'coop' ID: <object type="image/svg+xml" id="coop"
class="img-responsive ico-box" data="svg/ico-coop.svg"></object>

3. Include the script: <script type="text/javascript">

// Init your Vivus instance (with your own settings, this is just an
example)
var myVivus = new Vivus('coop', {type: 'delayed', duration: 150}),

// Then listen to the event of your choice to restart the animation
myVivus.parentEl.addEventListener('click', function () {
myVivus.reset().play();
})
</script>

**Comment by marcelomgerais** [comment]
hi max. i made this but does not works... see it in action:
[http://bit.do/eQunB](url)
the first icon on first box (above + 5 MIL).
tks a lot!!

**Comment by maxwellito** [comment]
Thanks for providing the page where you use it. The problem is the animation is triggered when the SVG is in the window viewport. Sadly, by using the sliding system, Vivus cannot know when the animation should start. 
Somebody had the a similar issue in the past (but couldn't find it back), the solution was to start manually the animation when the panel get open. But I don't know how it works.
