### ISSUE TITLE
Drawing Point

### ISSUE THREAD

**Issue by avidsapp** [maxwellito/vivus#218]
No issue, but is there a way to specify an SVG layer that acts as the drawing point? This is intended to simulate a welding path where the electrical arc would serve as the drawing point and lead the stroke animation. [See this video intro as an example](https://www.youtube.com/watch?v=fjkmombCID4).

**Comment by maxwellito** [comment]
Hi there,

Sadly there's no way to track the top of the line for further animation.
Everything is between the hands of CSS. Sorry about that.

**Comment by avidsapp** [comment]
Bummer. Thanks
