### ISSUE TITLE
Delay Start of Animation

### ISSUE THREAD

**Issue by tylerstrebeck** [maxwellito/vivus#219]
Hi, this is another question, not necessarily an issue. Is it possible to delay the start of the animation? For example, I have 4 different SVGs next to each other, and I want to delay the start of the animation for one of them. Thank you!

**Comment by maxwellito** [comment]
Hi there,

I'm afraid there's no built in solution for that. A bad and easy trick I have in mind would be to set a callback for the first SVG to be animated. In this callback, you start manually the animation of the last one. But that might not fit your needs at all.

```js
let myLastAnimation  = new Vivus('your-last-svg',  {start: 'manual', ...})
let myFirstAnimation = new Vivus('your-first-svg', {...}, () => {
  myLastAnimation.play()
})
```
