### ISSUE TITLE
reverseStack dosnt work

### ISSUE THREAD

**Issue by zdimaz** [maxwellito/vivus#220]
Line view bottom-left to right-top, 
I wont go to reverse view init start
My code

			if($("#curve_line1").length){

				var curve = new Vivus('curve_line1', {
					reverseStack: true,
					type: "oneByOne",           // delayed, sync, oneByOne, script, scenario or scenario-sync
					file: "./images/curve-line.svg",
					duration: 200,
				});

			};

**Comment by maxwellito** [comment]
Hi @zdimaz, I'm afraid your ticket doesn't follow the guidelines from the issue template. Please provide a [Plunker](plnkr.co)/[JSfiddle](https://jsfiddle.net/) and steps to reproduce your problem. Thanks.
