### ISSUE TITLE
cant find path in VUE project with webpack

### ISSUE THREAD

**Issue by cc-doughnut** [maxwellito/vivus#222]
ERROR ：Cannot find the SVG in the loaded file
VUE-CLI project build with webpack
Please tell how to resolve this problem？

**Comment by maxwellito** [comment]
Please follow the instructions provided in the issue template. I won't be
able to help without reproducible steps or details :)

**Comment by cc-doughnut** [comment]
Im sorry that my english is too poor to fill the issue template
My problem is when i new the Vivus,I pass the string such as '../../assets/svg/hithere.svg' to the variable of file.Then the error Cannot find the SVG in the loaded file : ../../assets/svg/hithere.svg occured in the console.
I think this happed may have some related to the webpack config.
Appreciate a lot!

**Comment by maxwellito** [comment]
Don't worry about your English :) Im not a native english speaker as well

I see your problem now. I think you start Vivus with a link to your SVG
like if it was a JavaScript dependency. Vivus doesn't work like this, it
will load the SVG when executed in the browser.
So you need to serve your SVG via your webserver then provide the URL of
the SVG, something like "http://localhost:8080/assets/svg/hithere.svg".


new Vivus("http://localhost:8080/assets/svg/hithere.svg");

Or

new Vivus("/assets/svg/hithere.svg");

**Comment by maxwellito** [comment]
Does it work? :)

**Comment by cc-doughnut** [comment]
Thank you for asking！
Sorry reply late！
what I have done is as below:
1.I make a component which containes vivus.I initialize and set attributes in the component.So I can import the component in other component by using the tag such as <xxx-svg></xxx-svg>
2.The parameters such as file is passed by props.For example
                   <xxx-svg file=“../../assets/svg/hithere.svg”></xxx-svg>
3.The point is webpack cant parse the path variable FILE when build the project.
4.So I parse the file manualy.For example 
                   this.svgPath=require('../../assets/svg/hithere.svg')
                   <xxx-svg :file="svgPath"></xxx-svg>
Hope u understand!
GL!HF!

**Comment by maxwellito** [comment]
So, I'm afraid Vivus cannot take a SVG content as parameter. The SVG must
be inline or you must provide the path to load it. You can't use require to
load an SVG and give it to Vivus, it won't do anything.

Your SVG must be available via your HTTP server. Then you can initialise
Vivus.

I might have made a mistake in my previous example, sorry about that.

In the case of '../../assets/svg/hithere.svg'. You must serve the 'assets'
folder on your http server, then you can access the SVG via
'/assets/svg/hithere.svg'.

So you can init Vivus with :
new Vivus(myDomElement, {file: '/assets/svg/hithere.svg'});

---------

If you use require, the component won't be dynamic. You can still do the
following:

var mySVG = require('../../assets/svg/hithere.svg');
// domElementContainer is your DOM element where you plan to put your SVG
domElementContainer.innerHTML = mySVG;
new Vivus (domElementContainer.querySelector('svg'));

And I'm not even sure it's gonna work

--------

I hope this helps :)

>

**Comment by cc-doughnut** [comment]
Its very kind of for helping me with the issue.
Im sorry for that I didnt express myself correct!
The step.2 in the last reply didnt work because the path was not right
The step.4 in the last reply worked and I will take that way in my project.
Regards!

**Comment by maxwellito** [comment]
😉
