### ISSUE TITLE
Stuck on scroll

### ISSUE THREAD

**Issue by charlespeters** [maxwellito/vivus#23]
using your wonderful library on this site http://moniquemaloney.com/
locally it works just as intended but live only loads after you scroll. not sure what's up.

**Comment by flyingfisch** [comment]
Hmm, that site doesn't seem to be loading for me... I get my default ISP not found page instead.

**Comment by flyingfisch** [comment]
Yep, seems to be down according to this too: http://www.downforeveryoneorjustme.com/www.moniquemaloney.com

**Comment by charlespeters** [comment]
try again?

On Wed, Jan 28, 2015 at 10:00 PM, Mark Fischer, Jr.

**Comment by maxwellito** [comment]
Nice SVG :-)
I had a look, and I guess it's because you're using the default option values when you instantiate your Vivus object.

```js
// Your code
new Vivus('floralpattern', {type: 'delayed', duration: 25});
```

So `start ` value is `inViewport` (default behavior). If you want is to load automatically once the page is loaded, set the value to `autostart`.

```js
// What you should try
new Vivus('floralpattern', {
    start: 'autostart',
    type: 'delayed',
    duration: 25
});
```

**Comment by charlespeters** [comment]
that totally worked thanks so much.
