### ISSUE TITLE
Trigger SVG to draw as soon as you see it (very large SVG)

### ISSUE THREAD

**Issue by frazerf** [maxwellito/vivus#231]
I've got a very large SVG (150vh) and it's drawing fine but only when I reach the end of the SVG, at which point the user has already scrolled passed the majority of the animation. Is there a way of starting the animation when it first comes in to view? I'm using start: inViewport but that still seems to wait until the enitre SVG is in view before triggering.

**Comment by maxwellito** [comment]
In this case I would recommend you to keep the `start` option to `manual`, and code the trigger that suits you. There are libraries that can help you about it. The 'inViewport' setting in Vivus doesn't provide much option and sadly doesn't fit every need.
