### ISSUE TITLE
Include Start delay without Loop

### ISSUE THREAD

**Issue by tuananhnp** [maxwellito/vivus#232]
Hi Max. I love Vivus Instant! After messing around, I've found the delayed start option very useful to manipulate animation sequence with several SVGs together. But I don't need looping, just a stop at the end after playing. I would like to know if there is anyway to introduce Start delay into SVG animation without Loop?

**Comment by maxwellito** [comment]
Hi there,

Sorry about the delay and thanks for your kind words. Sadly Vivus Instant doesn't offer a parameter to set initial delay. If it's for your personal use, I can try to find what to hack in the code to give help you.

**Comment by tuananhnp** [comment]
Hey, I just figured out how to delay the other SVGs' initialization using setTimeout function, which works pretty well. Thank you for your response. Cheers!

**Comment by maxwellito** [comment]
Awesome! Good job :)
