### ISSUE TITLE
Is vivus deprecated?

### ISSUE THREAD

**Issue by verbose9** [maxwellito/vivus#233]
The repo is not updated for 2 years and I want it in production.

**Comment by maxwellito** [comment]
Not deprecated, but does what it is meant to. There's no major update in the pipeline, and I refuse to add features (or it will end up making coffee as well). I keep it alive if something is broken. I think the last major one was when Chromium inserted a breaking change and the whole library was broken. I had to release a patch and also provide an example to the Chromium bug tracker.
