### ISSUE TITLE
Beginner, unable to use 

### ISSUE THREAD

**Issue by meetdilip** [maxwellito/vivus#236]
**Vivus version**: 0.4.6

**Browser**: Firefox 88 - 64-bit on Ubuntu 20.04

**Steps to reproduce it**:

I was expecting the following HTML + SVG files I placed on the desktop will give me an animated display when opened with a browser. The SVGs work nicely with Vivus Instant. I am trying to animate them locally.  Please see the HTML code I am using 

```
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Vivus Test</title>
  </head>
  <body>
  
  
    <h1>My Sample text</h1>
    
    <div id="my-div"></div>

<script>
  new Vivus('my-div', { duration: 200, file: '/circ.svg' }, myCallback);
</script>

   <script src="https://cdnjs.cloudflare.com/ajax/libs/vivus/0.4.6/vivus.js"></script>
   
  </body>
</html>
```
It would be nice know what else should be in this file for the SVG animation ( attached as zip ). Thanks

[circ.zip](https://github.com/maxwellito/vivus/files/6406007/circ.zip)

*[note]*
Please have a minimum of politeness. There's unfortunately only me as contributor/maintainor which help on my free time, I'm not the Amazon customer service or your Mom. I don't ask to send me flowers and tell me how amazing Vivus is (that won't make me help you quicker). But please try to do as much as you can before opening an issue: check that no closed issue mention a similar problem, that your script is executed correctly (conflicts, race conditions...).. Thanks :)
*[/note]*

**Comment by maxwellito** [comment]
Hi there,

From the HTML you're sharing, I can notice one thing. You instantiate/use
Vivus before loading the library. You must switch the two <script> tags.
About local development, you must serve your fila via a webserver. Consider
installing "http-server" from NPM or find another way to serve your local
file.
Then it should do the trick :)

**Comment by meetdilip** [comment]
Thanks for the response. I have XAMPP installed. I placed `vivus-master` in `/opt/lampp/htdocs` and then chose `test/manual/index.html` . It looks like the test is not successful because I do not get any animation

![test vivus 2](https://user-images.githubusercontent.com/6965443/116766388-da7da780-aa47-11eb-9cf7-b80e87e24178.gif)

**Comment by meetdilip** [comment]
I moved the script tags just after the body, but with no luck

SVG looks like 
```

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="210mm"
   height="297mm"
   viewBox="0 0 210 297"
   version="1.1"
   id="svg8"
   inkscape:version="1.0.2 (1.0.2+r75+1)"
   sodipodi:docname="circ.svg">
  <defs
     id="defs2" />
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="0.35"
     inkscape:cx="400"
     inkscape:cy="560"
     inkscape:document-units="mm"
     inkscape:current-layer="layer1"
     inkscape:document-rotation="0"
     showgrid="false"
     inkscape:window-width="1312"
     inkscape:window-height="699"
     inkscape:window-x="54"
     inkscape:window-y="30"
     inkscape:window-maximized="1" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1">
    <circle
       style="fill:none;stroke:#000000;stroke-width:0.529167"
       id="path833"
       cx="96.706818"
       cy="134.39049"
       r="34.225163" />
    <circle
       style="fill:none;stroke:#000000;stroke-width:0.529167"
       id="path835"
       cx="69.142792"
       cy="191.39706"
       r="11.093869" />
    <circle
       style="fill:none;stroke:#000000;stroke-width:0.529167"
       id="circle837"
       cx="129.48465"
       cy="191.39706"
       r="11.093869" />
    <circle
       style="fill:none;stroke:#000000;stroke-width:0.529167"
       id="path839"
       cx="98.171478"
       cy="207.77689"
       r="59.820881" />
  </g>
</svg>

<script>
  new Vivus('svg8', {duration: 200}, myCallback);
</script>
```
HTML is

```
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link src="/custom.css" type="stylesheet"></link>
  
  

    <title>Vivus Test</title>
  </head>
  <body>
  
   <script>
  new Vivus('svg8', { duration: 200, file: '/circ.svg' }, myCallback);
</script>

   <script src="https://cdnjs.cloudflare.com/ajax/libs/vivus/0.4.6/vivus.js"></script>
 
  
    <h1>My Sample text</h1>
    
    
    <div id="svg8"></div>

  </body>
</html>
```

The documentation said that there should be some definition of size. So I used a custom.css with 

```
.sais {
height: 250px;
width: 250px;
}

But I am not sure where to use it in HTML. Thanks for your time. 
```

**Comment by maxwellito** [comment]
Any error in the web console?

Also, I see you didn't change the order of the script tags. They should be
like in the following order.

<script src="https://cdnjs.cloudflare.com/ajax/libs/vivus/0.4.6/vivus.js"></script>

<script>
  new Vivus('svg8', { duration: 200, file: '/circ.svg' }, myCallback);
</script>

**Comment by meetdilip** [comment]
Thanks. I changed the script order and tried again. Got this in console

>Uncaught ReferenceError: myCallback is not defined
    <anonymous> file:///opt/lampp/htdocs/vivus/anim.html:19

HTML is now
```

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link src="/custom.css" type="stylesheet"></link>
  
  

    <title>Vivus Test</title>
  </head>
  <body>
  
<script src="https://cdnjs.cloudflare.com/ajax/libs/vivus/0.4.6/vivus.js"></script>

<script>
  new Vivus('svg8', { duration: 200, file: '/circ.svg' }, myCallback);
</script>
   
 
  
    <h1>My Sample text</h1>
    
      <div class="sais">
    
    <div id="svg8"></div>

      </div>
   
  </body>
</html>
```

**Comment by meetdilip** [comment]
I found a workaround. Modified the index.html page in `Test` so that I can use my choice of SVG and animate it. Thanks.

A request. Is it possible to have something like Vivus Instant locally so that I cannot simply animate my SVGs but also export it ? If yes, would be delighted to know how :)

**Comment by maxwellito** [comment]
By having Vivus Instant locally, what do you mean? Having the code working locally on your machine so you can generate animated SVG offline? If so, clone [vivus-instant](https://github.com/maxwellito/vivus-instant) (or download the [zip](https://github.com/maxwellito/vivus-instant/archive/refs/heads/master.zip)) and open `index.html` in it :)

**Comment by meetdilip** [comment]
Thanks. I wanted to create animated SVGs locally. It is working fine without XAMPP or VSCode Live Server. Have a nice time. :)
