### ISSUE TITLE
Support for Play Pause

### ISSUE THREAD

**Issue by kpomservices** [maxwellito/vivus#237]
I used vivus for animating the SVG. its very good for animating the svg.

Do we have any option or way to pause / pause animation?
Suppose if the svg has multiple path / shape elements (say circle, rectangle, line) i wanted to pause at each shape / path. 

Please suggest how to achieve the play and pause using vivus.

**Comment by maxwellito** [comment]
Hi there,

Vivus already provide a play and pause method. However it's for the whole
animation. If you want to have a granular control over each shape of your
SVG, I'm afraid you will have to split each shape in different SVG that you
will control independently.

**Comment by kpomservices** [comment]
@maxwellito  Thanks for your response.

play / pause at the whole animation is also fine for me now,  
Pls provide details how to play and pause. i couldn't find it in the documentation.

Thanks

**Comment by maxwellito** [comment]
You can see the [methods in the readme](https://github.com/maxwellito/vivus#methods).

```js
// Create your Vivus instance
const myVivus = new Vivus('my-svg-id', {start: 'manual'});

// ..then when you need
myVivus.play();

// ..then when you need to stop
myVivus.stop();
```

**Comment by kpomservices** [comment]
Ok Thanks very much. i thought play() will play only from start of svg.
Its working fine.
