### ISSUE TITLE
[Error Fix]: There is a grammatical error on the index page.

### ISSUE THREAD

**Issue by HAYVENO** [maxwellito/vivus#242]
###Hello Maxwellito, 

Great job with this JS library.

However, there is a grammatical error on the  hero section of the`index.html` page and I will like to submit a PR to fix it.

**Vivus version**: v0.4.6

**Comment by HAYVENO** [comment]
I have made a PR.

**Comment by maxwellito** [comment]
Thanks for your PR (and your kind words)! I'm terrible with speling mistakes :-D
