### ISSUE TITLE
Jquery Function callbacks fails the SVG animation

### ISSUE THREAD

**Issue by Techno-Tut** [maxwellito/vivus#25]
Hey maxwellito,
This Script is great and working fine, I am quite happy with the results and the truth that animating an svg can be that easy. But I found a problem when ever I try callback a function using jquery that fails the animation but when I try the same thing with the JavaScript it works fine. First I thought that it may be a syntax error but I checked all the syntax, I found nothing wrong. But the JavaScript seems to work fine. I am not sure that is mine problem or did any one else faced it. any help i will appreciate,

**Comment by maxwellito** [comment]
Not sure to see the problem. Can you show me a page where I can see your code? Or a jsFiddle? Thanks :)

**Comment by Techno-Tut** [comment]
here is the link :https://www.mediafire.com/?dv1ypot2ybtt58z

there are two files doing same thing they fade in the text after animation. but the JavaScript make it seems correct but jquery does nothing.

**Comment by jolic** [comment]
It's not a vivus issue!

Change your line to:

...
$('#p').css({opacity:1});
...

**Comment by Techno-Tut** [comment]
Thanks it works and sorry for  this.

**Comment by maxwellito** [comment]
Thanks @jolic I didn't had time to look at it :-)
