### ISSUE TITLE
Is a non-automatic One By One drawing possible?

### ISSUE THREAD

**Issue by eromsis** [maxwellito/vivus#253]
Hi Max,

I've been using Vivus Instant for a project I'm working on and I think it's really great, however, I was wondering if it's possible to import an image that I've converted to an SVG and view the construction of the image line by line at my own pace? My knowledge of JS is less than minimal, hence using Vivus Instant.

To clarify, this isn't really an issue so you can close it fairly quickly I reckon, I just needed some way to contact you about Vivus. I've messaged you previously on Behance but didn't know if that was still something you used so am trying to grab you here - sorry if that is inappropriate. There is more context in that message on Behance by the way.

Kind regards

**Comment by maxwellito** [comment]
Hi there,
Sorry I didn’t see your message. I kinda left a lot of old accounts. Would it be possible for you to share this svg? If it’s something a bit too private we can find another solution.

My assumption is your SVG is made out of filled paths instead of borders (strokes). This is why you cannot see it animated in Vivus instant.

**Comment by eromsis** [comment]
I get it, I have my fair share of dead accounts! Do you still use twitter/X? I'm the same handle on there, if you follow me I could resend the message through a DM on there? 

It's not that the image doesn't animate, I'm just trying to find out if there is a way for me to almost go node to node with a button click, rather than a full start to finish animation?

**Comment by maxwellito** [comment]
Yes, reach out on twitter/x. I still go there time to time.
About the animation you’re looking to achieve, make a search on previous issues. It came up at some point

**Comment by eromsis** [comment]
Cool, I've DM'd you there.

I will have a look back and see if I can find something that suits what I'm trying to achieve as well!

Happy for this to be closed now.
