### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by mg** [maxwellito/vivus#27]
Would be very much appreciated.

**Comment by maxwellito** [comment]
Ok, I'll have a look to do it. I was planning to release the version 0.2 (check the dev branch), maybe I can integrate this as part of the plan.

Can I ask you something? I always used Bower to manage my frontend dependencies, how do you use npm for that? I mean, Vivus is not really node package, I find confusing to put frontend libraries/frameworks and node packages at the same place. I feel old school :-)

**Comment by mg** [comment]
Happy to.

I've completely moved to Webpack (http://webpack.github.io/) for client code. So in my starting js file for the browsers I require a package (or use ES6's import) that requires more packages etc. Webpack (this applies to browserify (http://browserify.org/) as well) parses the starting js file and from there builds all the required/imported files into one javascript file (usually called bundle.js). 

The index.html then simply includes this js file the old way (using script tag). 

The insane thing about Webpack is that you are not restricted to including just js files. It handles css files, less files, sass files, svg, json, text files, almost everything (even images encoded on the fly as Base64) and bundles it all into one js file that you include in your html. 

So if you want to use something from the npm world in your client code (presuming that the npm package doesn't depend on something that isn't available in the browser environment, like a MySQL database) you just install it with npm and then require it in the js file you are using it and Webpack will take care of the rest.

**Comment by maxwellito** [comment]
Oh OK, make sense in my head now. That's pretty clever, thanks for this lesson. 

Do you know if my `package.json` is valid? I think I did something stupid when I set it up long time ago, which is to use the default value for the property `main`: `index.js`. I guess I have to replace it with `dist/vivus.min.js`, right?

**Comment by mg** [comment]
Not sure, don't have that much experience with publishing packages to npm. But I'll have a better look at it tomorrow, going to sleep now (GMT+0)

**Comment by maxwellito** [comment]
Thanks for your help!

I should go to bed too, I'm on the same timezone :)

**Comment by mg** [comment]
Ok so first thing you need to do is build a CommonJS version of your code and put it into e.g. dist/vivius.node.js or something like that. Don't bother building a minified version for node, we just let our build tools take care of that.

Second, you need to loose the IIFE for this file, the CommonJS standard takes care of putting everything into its own namespace. 

Basicly take this:
```
'use strict';
(function () {
  'use strict';

... your code

  window.Vivus = Vivus;
}());
```

and replace it with this:

```
... your  code...
module.exports= Vivus;
```

Now point the main entry in package.json to this file and you should be good to go.

**Comment by gching** [comment]
https://github.com/umdjs/umd

**Comment by maxwellito** [comment]
Good, thanks @mg for this explanation. I just need to add a simple Gulp task and create a layout to wrap Vivus.

@gching, to make it compatible CommonJS and AMD I have to use this [pattern](https://github.com/umdjs/umd/blob/master/commonjsAdapter.js), right?

*Please, I hope nobody else will come and ask me to make it compatible with another format. :-)*

**Comment by gching** [comment]
I believe so, but to be honest, I am new to the scene for this module stuff and the different patterns so perhaps if @mg or anyone else knows if this is the correct one, do let us all know!

Sorry for my lack of knowledge :<!

**Comment by maxwellito** [comment]
@afc163 made a [PR](https://github.com/maxwellito/vivus/pull/37) which looks good to me. Just wondering if it's wise to have the same file for frontend and npm, but it shouldn't break anything, the fallback look right.

I would appreciate if NPM + Browserify users could give thein point of view :)

**Comment by maxwellito** [comment]
Ok, apparently nobody seems to be able to help (I can't blame, I'm in the same position).
So let's ask my JavaScript sensei : @yrezgui

Yacine, what do you think of this [pull request](https://github.com/maxwellito/vivus/pull/37)? Especially the way to package the library (file `src/_build.js`). 
Thanks :)

**Comment by mg** [comment]
It looks good to me. Im not very familiar with AMD but Ive seen patterns like this before, e.g.:

https://github.com/gionkunz/chartist-js/blob/develop/dist/chartist.js

**Comment by maxwellito** [comment]
Thanks @mg, I merged the PR. I'll try it tonight, then once my unit test finished (about other features) I release the v0.2

**Comment by mg** [comment]
Did try it just now, got version 0.1.2:

```
npm http GET https://registry.npmjs.org/vivus
npm http 200 https://registry.npmjs.org/vivus
npm http GET https://registry.npmjs.org/vivus/-/vivus-0.1.2.tgz
npm http 200 https://registry.npmjs.org/vivus/-/vivus-0.1.2.tgz
vivus@0.1.2 node_modules/vivus
```

The dist/vivus.js file contains the AMD/CommonJS code at the bottom though

**Comment by maxwellito** [comment]
Try again :)
Sorry, I thought the update was automatic after a release.

**Comment by maxwellito** [comment]
@mg Is it working?

**Comment by mg** [comment]
Yup
```
npm http GET https://registry.npmjs.org/vivus
npm http 200 https://registry.npmjs.org/vivus
npm http GET https://registry.npmjs.org/vivus/-/vivus-0.2.0.tgz
npm http 200 https://registry.npmjs.org/vivus/-/vivus-0.2.0.tgz
vivus@0.2.0 node_modules/vivus
```
Good job, thanks for this.
