### ISSUE TITLE
Publish as webjar

### ISSUE THREAD

**Issue by csgruenebe** [maxwellito/vivus#38]
It would be nice to be able do download vivus as webjar.
See: 
  - http://www.webjars.org/
  - http://www.webjars.org/contributing

We could do the initial work for you and you could fork it and maintain it.
Or we can do all the work and mantain it. As you like :smile: 

Here is the tested **pom.xml** for the webjar. Just type mvn package.
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>org.sonatype.oss</groupId>
        <artifactId>oss-parent</artifactId>
        <version>7</version>
    </parent>

    <packaging>jar</packaging>
    <groupId>org.webjars</groupId>
    <artifactId>vivus</artifactId>
    <version>0.1.2</version>
    <name>vivus</name>
    <description>WebJar for vivus</description>
    <url>http://webjars.org</url>

    <developers>
        <developer>
            <id>maxwellito</id>
            <name>maxwellito.com</name>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>MIT</name>
            <url>https://github.com/maxwellito/vivus/blob/master/LICENSE</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/[REPONAME]</url>
        <connection>scm:git:https://github.com/[REPONAME].git</connection>
        <developerConnection>scm:git:https://github.com/[REPONAME].git</developerConnection>
        <tag>HEAD</tag>
    </scm>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <upstream.version>0.1.2</upstream.version>
		<upstream.url>https://raw.githubusercontent.com/maxwellito/vivus/v${upstream.version}/dist</upstream.url>
        <destDir>${project.build.outputDirectory}/META-INF/resources/webjars/${project.artifactId}/${upstream.version}</destDir>
    </properties>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>wagon-maven-plugin</artifactId>
                <version>1.0-beta-4</version>
                <executions>
                    <execution>
                        <id>download-js</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>download-single</goal>
                        </goals>
                        <configuration>
                            <url>${upstream.url}</url>
                            <fromFile>vivus.js</fromFile>
                            <toDir>${destDir}</toDir>
                        </configuration>
                    </execution>
                    <execution>
                        <id>download-min-js</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>download-single</goal>
                        </goals>
                        <configuration>
                            <url>${upstream.url}</url>
                            <fromFile>vivus.min.js</fromFile>
                            <toDir>${destDir}</toDir>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5.1</version>
            </plugin>

            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>1.6.5</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>sonatype-nexus-staging</serverId>
                    <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                    <autoReleaseAfterClose>true</autoReleaseAfterClose>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by maxwellito** [comment]
Hi,
I have to be honest, it's the first time I hear about WebJars. We already are on Bower and JSdelivr, and soon on NPM. I'm not against the idea of having a library manager, but I have to admit I got scared when I saw your big XML file.

Can I ask you the advantage of WebJars compared to NPM, Bower or a simple CDN?

**Comment by csgruenebe** [comment]
NPM and Bower are mainly used by UX guys for frontend only applications. 
We build a Java Application (backend) with gradle (or maven) and have a frontend component in AngularJS.
And we want only one buildfile in gradle. With webjars you can define a JavaScript Library as dependency the same way you would define a Java Library like Spring Boot. Here is an example of the gradle build file:
```
dependencies {
        // Java Dependency
        compile 'org.springframework.boot:spring-boot-starter-web'
        // JS Dependency
        runtime 'org.webjars:angularjs:1.3.13'
        runtime 'org.webjars:angular-material:0.7.1'
```
So we don't need bower/npm to download the javascript libs. It happens together with the java libs.
In the app we can just reference the libs in the view like this:
```
<script src="webjars/angularjs/1.3.13/angular.js"></script>
<script src="webjars/angularjs/1.3.13/angular-resource.js"></script>
```

It is just another approach similar to npm and bower but just from another point of view. 
I prefer this approach to bower/npm because I have only one buildfile now.

And this big pom.xml is just the way of telling webjars.org where all your files are so that it can build a webjar for vivus. Normally the webjar org people should maintain it. So if you don't mind I would create a github project and ask the webjar guys to fork it, so that it will be included in webjars.org for the future. So you should have no future work. You just release versions on GitHub and the webjar guys will then make a release as webjar depending on that version.

I already did this initial setup for hello.js in consultation with the guys from hello.js. 
You can see it here: https://github.com/comsysto/hello.js.webjar

**Comment by maxwellito** [comment]
I'm ok to have the `pom.xml` file in this repo, except if you think it would be easier for you to manage it from your fork (Do you have to update it manually or it will be automatic a every release?).

In which case this file should be updated? At every new version?

The only thing is, if we decide to put it in this repo, can you allow me to make you responsible for it? Just if we have an issue or question about it, just having the right to mention you to join the conversation :)

**Comment by csgruenebe** [comment]
If you put it in your repo, all your other stuff will be forked to a webjars.org repo and then you have zombie files there.
I will start it of with my repo which will be forked, and as I unterstand it then the guys from webjars.org will take it from there and release updates when new versions are available. So there should be nothing to do from there on out.
But just in case you need help in the future you can mention me :)

I raised the issue on webjars org here: https://github.com/webjars/webjars/issues/888
Now we have to wait for the guys at webjars org to integrate it.

**Comment by maxwellito** [comment]
Oh! Brilliant! :-)
Is there anything I should mention you in the future? If I move the dist files or something? Or a new release?

**Comment by csgruenebe** [comment]
I just need to know if you add extra files to the release or the filenames of the released files change.
If all stays the same the guys from webjars should be fine. Normally when a new version comes out people will click on the "request new version" on the webjars page and the guys from webjars should do it. So it should be fine as long as you don't change the released files in any way :)

**Comment by maxwellito** [comment]
Excellent!
I take note and will contact you if the released files changes. Thanks for your work :)

**Comment by erquhart** [comment]
> NPM and Bower are mainly used by UX guys for frontend only applications.

lol
