### ISSUE TITLE
Lines not joining properly

### ISSUE THREAD

**Issue by radius** [maxwellito/vivus#39]
The Plunk:
http://plnkr.co/edit/9dZEGHLSg2JA3n7CrIMY?p=preview

I am drawing a simple triangle, and as you can see from the Plnkr, the final line is not joining the way it should (in the non-animated version). 

I am setting the stroke-miterlimit property, but it still doesn't seem to be working. Any ideas?

**Comment by maxwellito** [comment]
Ewwww... I thought I fixed it, and I actually did, but I should make it better :-S 
I put it in my list.

For now, what you can do add the attribute `selfDestroy` with the value `true`.

So your code would look like 
```js
new Vivus('Layer_2', {
  type: 'async',
  duration: 50,
  selfDestroy: true
}, function () {
  console.log('animation done');
});
```

The reason is, by using `selfDestroy` it remove all `stroke-dasharray` and `stroke-dashoffset` attribute from all path elements in the SVG.

Hope it helps :)

**Comment by radius** [comment]
Thanks! That worked for me. 
I still don't understand why the final values of stroke-dasharray don't work as expected, but I guess since this whole technique is a clever workaround we can't expect too much :)

**Comment by Pixelous** [comment]
Hi @maxwellito ,

your solution does not help when using:

type: 'delayed',
duration: 200,
pathTimingFunction: Vivus.EASE_OUT,
animTimingFunction: Vivus.EASE_OUT,

Can you give another fix please?

**Comment by maxwellito** [comment]
JSfiddle please

**Comment by Pixelous** [comment]
Please take a look at it by following this link http://demo.themeuniverse.net/pear/demo-8/ See animated triangle at the bottom of the page above

Would you like to order a project?

text.

**Comment by Pixelous** [comment]
I tested

selfDestroy: true

and removed it as it does not help. It helps to to join the triangles lines but it looks not smooth, lines join immediately without animation.

**Comment by maxwellito** [comment]
Ok, I found out why. I need to fix a little problem for SVG with 1 path. For now just use this options object:

```js
{
	type: 'oneByOne',  // << that's the fix
	duration: 200,
	pathTimingFunction: Vivus.EASE_OUT,
	//animTimingFunction: Vivus.EASE_OUT,
	start: 'manual',
	selfDestroy: true
}
```

But personal advice, avoid using `pathTimingFunction` and `animTimingFunction` on such a single path SVG. You just double the ease.

**Comment by Pixelous** [comment]
Animation still looks not smooth for me. Is it possible to fix it without using

`selfDestroy: true`

?

**Comment by maxwellito** [comment]
The end will never look smooth.
