### ISSUE TITLE
Need Commas in Path Elements?

### ISSUE THREAD

**Issue by jordan-wright** [maxwellito/vivus#41]
I have some paths that look like this:

```
<path stroke:#000000;stroke-width:1px;stroke-linecap:butt; d="m 57.6 24.2 2.2 2 c 2.6 -2.8 6.2 -4.4 10 -4.4 3.8 0 7.5 1.6 10 4.4 l 2.2 -2 c -3.1 -3.5 -7.6 -5.4 -12.2 -5.4 -4.7 0 -9.1 2 -12.2 5.4 z"/>
```

Vivus doesn't seem to recognize these paths, as they aren't drawn. I saw in #40 that you mentioned the use of commas - are these necessary in Vivus SVGs?

**Comment by maxwellito** [comment]
Nope, it's not due to missing commas. But thanks for checking the other issues before post one :-)

Your DOM element got an invalid syntax, it should be:

```html
<path stroke="#000000" stroke-width="1" stroke-linecap="butt" d="m 57.6 24.2 2.2 2 c 2.6 -2.8 6.2 -4.4 10 -4.4 3.8 0 7.5 1.6 10 4.4 l 2.2 -2 c -3.1 -3.5 -7.6 -5.4 -12.2 -5.4 -4.7 0 -9.1 2 -12.2 5.4 z" fill="none"></path>
```

The properties are the same, I just added `fill="none"` because the default behavior is to fill all path in black. But maybe you got a CSS rule which override that.

**Comment by jordan-wright** [comment]
Thanks for the quick response! I'll give that a shot.

To show you what I'm doing - I'm currently trying to animate svgs from flaticon.com by importing them in inkscape, ungrouping everything, and changing the objects to paths. Then, I remove all the inkscape fluff that isn't needed.

Do you see any issues with doing things this way? I mean, I should just end up with paths. Maybe the issue is the lack of the ```fill``` attribute. I will let you know if that fixes it.

Thanks again for your help!

**Comment by maxwellito** [comment]
There's no issue with that. I just remind you Vivus is made to animate `stroke` on SVGs, not `fill`. Some icons from flaticon.com might look weird without fill.

I can help you with two things:

1. If you have a lot of SVG to clean, I recommend you [svgo](https://github.com/svg/svgo): SVG Optimizer is a Nodejs-based tool for optimizing SVG vector graphics files. 
But if you don't want to use node and just optimise few SVGs, use [svgomg](https://jakearchibald.github.io/svgomg/), it's a UI for the module I just mentionned.

2. If you insert your SVGs inline in your HTML, you can use CSS to override the rules.

```css
svg path {
  stroke: "#FFFFFF";
  fill: none;
}
```

I recommend you to use a class and not `svg` directly :-)
