### ISSUE TITLE
Animation type request: by path length

### ISSUE THREAD

**Issue by raphaelbastide** [maxwellito/vivus#42]
I imagine an option that delays the drawing of small path at the end of the animation. In this case, the details of the drawing are added in the end only. For example, in the case of a face, it can be nice to simulate a drawer’s process and trace eyes details in the end, after the main paths of the silhouette.
I can imagine that the `oneByOne` type simply respect the initial order of the paths in the SVG, but I think designers shouldn’t have to care about the animation while they design a shape.
Maybe this can be done simply by ordering paths drawing by length. What do you thin?

**Comment by maxwellito** [comment]
Hi,
I completely understand that designer shouldn't care about the order of their layers. But using the layer order was the most natural default behavior to implement.

In your case you want some control over the drawing scenario, this is why I recommend you check the type [`scenario`](https://github.com/maxwellito/vivus#scenario).

It give you the possibility to define the start and duration of each path element. In this case, the layer order doesn't matter. But it might take you some time to script your SVG.

Check the [`readme.md`](https://github.com/maxwellito/vivus#scenario) file and come back to me if you have any questions.

**Comment by raphaelbastide** [comment]
Thank you, I am aware about the type `scenario` I actually think about an automated order able to treat images with a lot of paths.

**Comment by SLQ-CommWeb** [comment]
Thanks for making this fantastic js file but I can't get it to work via external svg file. I have scanned this thread and looked at the methods to construct it with the object tag and went through the patch test "showMySVGInsideThisElement" (inserting svg object into the span) but it comes up with this error:

'Uncaught ReferenceError: Pathformer is not defined' which seems to stem from the vivus.js file (line 426: Vivus.init.

Can you show a working example in JsFiddle/JsBin?

**Comment by maxwellito** [comment]
Sorry for the late reply but yes, an example on JSfiddle would be amazing. But create a new issue for it :)

**Comment by maxwellito** [comment]
At the moment I don't plan to implement this kind of features. But I found a way to hook this feature.

```js
new Vivus('yourSvgId', { 
    type: 'oneByOne',
    onReady: function (obj) {
      var i, 
        counter = 0,
        newMap = obj.map.sort(function(a,b) {
          return b.duration - a.duration
        });

      for (i = 0; i < newMap.length; i++) {
        newMap[i].startAt = counter;
        counter += newMap[i].duration;
      }

      obj.map = newMap;
    }
  });
```

This trick wait the SVG to be ready to reformat the map in the order of path length. All other parameters are the same. Feel free to put this callback into an independent function to use it many times. You will need the `v0.2.0` to make it work.
