### ISSUE TITLE
Invalid path attribute error

### ISSUE THREAD

**Issue by RU-Alex** [maxwellito/vivus#44]
i am getting loads of those errors (chrome 40)

Error: Invalid value for <path> attribute d="ML135.895,198.852L377.182,198.852L377.182,126.803L448.269,1.665"
vivus.min.js:7 r.pathMakervivus.min.js:7 r.scanvivus.min.js:7 rvivus.min.js:7 n.initvivus.min.js:7 (anonymous function)

for this kind of polylines:
<polyline fill-rule="evenodd" clip-rule="evenodd" fill="none" stroke="#FBBA00" stroke-width="6.7401" stroke-miterlimit="10" points="135.895,198.852 377.182,198.852 377.182,126.803 448.269,1.665 	"/>

any pointers much appreciated?

**Comment by maxwellito** [comment]
From what I can see, the values of your `polyline` element are not correct. It's not even related to Vivus. I can't display an SVG with this values. 

From what I know, the `L` right after the `M` shouldn't be there. I tried and I displayed the SVG.

Can you post the code of your SVG to have a quick look please? :-)

**Comment by RU-Alex** [comment]
sure! it's exported from Illustrator and also running it through svgo doesn't seem to help...
please find the code below or get the file here: http://wartegarten.de/test_ai.svg

`<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="test" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="451.199px" height="303.801px" viewBox="0 0 451.199 303.801" enable-background="new 0 0 451.199 303.801"
	 xml:space="preserve">
<g>
	<polyline fill="none" stroke="#FBBA00" stroke-width="6.7401" stroke-miterlimit="10" points="135.895,198.852 377.182,198.852 
		377.182,126.803 448.269,1.665 	"/>
	<line fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" x1="0" y1="104.148" x2="14.547" y2="104.148"/>
	
		<line fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" x1="0.527" y1="156.239" x2="12.164" y2="156.239"/>
	
		<line fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" x1="6.609" y1="104.952" x2="6.609" y2="154.922"/>
	<polyline fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" points="7.662,131.121 34.372,131.121 
		34.372,274.177 	"/>
	<polyline fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" points="35.688,141.167 58.962,141.167 
		58.962,217.848 34.109,217.848 	"/>
	<polyline fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" points="35.688,131.912 56.316,131.912 
		69.534,131.912 71.391,132.452 	"/>
	<polyline fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" points="75.09,122.933 66.36,144.338 
		57.91,144.338 	"/>
	<polyline fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" points="59.489,180.566 80.381,180.566 
		95.177,165.757 136.961,165.757 136.961,198.286 136.961,243.241 	"/>
	<polyline fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" points="94.125,150.42 101.667,157.963 
		183.76,157.963 	"/>
	
		<line fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" x1="136.697" y1="158.359" x2="136.697" y2="165.757"/>
	<polyline fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" points="80.118,181.633 80.381,180.566 
		97.441,197.615 135.907,197.615 	"/>
	<polyline fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" points="97.441,197.615 81.696,232.13 
		81.696,287.395 	"/>
	
		<line fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" x1="58.962" y1="260.421" x2="58.962" y2="276.811"/>
	
		<line fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" x1="59.753" y1="267.82" x2="80.645" y2="267.82"/>
	<polyline fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" points="82.501,267.029 93.86,254.076 
		93.86,239.266 84.226,229.629 	"/>
	<polyline fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" points="112.896,198.286 96.639,214.544 
		151.771,301.665 172.662,299.557 	"/>
	
		<line fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" x1="58.962" y1="217.848" x2="99.153" y2="217.848"/>
	<polyline fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" points="101.271,218.915 124.007,218.915 
		124.007,197.758 	"/>
	
		<line fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" x1="60.818" y1="181.093" x2="82.236" y2="217.32"/>
	
		<line fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" x1="68.48" y1="193.257" x2="90.161" y2="193.257"/>
	
		<line fill="none" stroke="#FBBA00" stroke-width="4.0441" stroke-miterlimit="10" x1="34.898" y1="171.575" x2="58.173" y2="171.575"/>
</g>
</svg>`

**Comment by RU-Alex** [comment]
just figured out that setting the svg profile to SVG 1.0 (defaults to 1.1) on export seems to do the trick...
