### ISSUE TITLE
oneByOne with a callback before each new animation

### ISSUE THREAD

**Issue by michaelryancaputo** [maxwellito/vivus#45]
looking to create a type of keyframe animation between svg elements with a stop, or callback between each new animation starting.

I can't see a way to do this here, is that possible?

**Comment by maxwellito** [comment]
I'm afraid not :(

Sorry but this feature is not implemented. I tried to find a quick solution but I don't see any. If want this feature you will have to fork the code and implement it yourself. It's not ideal, but if you accept the challenge I will help you :)
