### ISSUE TITLE
r.contentDocument is null

### ISSUE THREAD

**Issue by tomas** [maxwellito/vivus#46]
I'm getting this error on Firefox 36.0.1 on OSX. Why might this be happening?

**Comment by maxwellito** [comment]
Mmm... Might be related to the previous issue. Can you create a jsFiddle to have look? Thanks

**Comment by tomas** [comment]
Actually I just created a fiddle and I'm getting the same error on Chrome. 

http://jsfiddle.net/jrk184nm/2/

Locally I'm just pointing to a file in the same host, so it's not due to CORS.

**Comment by maxwellito** [comment]
Ouch.. it looks like a bug from Vivus. I have to make a patch. It seems
related to the previous issue.

Sorry about that, but thanks for the ticket :-)

2015-03-23 16:35 GMT+00:00 Tomás Pollak <notifications@github.com>:

**Comment by maxwellito** [comment]
Hey @tomas 

Sorry for the delay. I made a local patch to see if I could fix the problem, and yes, now it works on Firefox (this patch is not deployed yet). But I mention your SVG does not have any shape with `stroke` values. And Vivus work on this, this is what the library animate.

I set up an example to show you http://maxwellito.github.io/drafts/vivus-issue-46/

You can have a look at the code from https://github.com/maxwellito/drafts/tree/gh-pages/vivus-issue-46

The first animation is from your code, the second one is a copy of it but with an SVG with `stroke` properties on shapes.

**Comment by tomas** [comment]
Nice, thanks for the quick action. Vivus rocks!

**Comment by maxwellito** [comment]
:-)
