### ISSUE TITLE
Entire path display before animation

### ISSUE THREAD

**Issue by kimwebParis** [maxwellito/vivus#51]
Hi!

your script is great, thanks very much!

I only have one problem: the entire path is showing before animation start. 
Do you have any idea how to fix this?

**Comment by maxwellito** [comment]
Hi!

Thanks for these kind words :)

About the SVG flash before the animation you can do the following. The trick consist to set a CSS rule to make the SVG transparent until Vivus has initialised the SVG. If you use Vivus for more than one SVG, I recommend you to store the callback in a separate function and have a more generic CSS rule across your SVGs.

```css
#yourSvgId {
  opacity: 0;
}
```

```js
new Vivus('yourSvgId', { 
    // your options
    onReady: function (obj) {
      obj.el.style.opacity = 1;
    }
  });
```

**Comment by kimwebParis** [comment]
that's perfect! Thank you
