### ISSUE TITLE
Auto-recording SVG delays while drawing

### ISSUE THREAD

**Issue by ulisesguerrero** [maxwellito/vivus#54]
Hello,

Do you know of any software that will record the stroke delays as they are drawn in real time? Instead of having to tweak the DOM to scenarize.

Thanks
Ulises

**Comment by maxwellito** [comment]
Mmm.. I'm afraid not. I would suggest you to use 'oneByOne', but you're
looking to reproduce the same timing as your drawing, so it won't work.
Sorry about that.
