### ISSUE TITLE
Strange behavior according to browser aspect ratio.

### ISSUE THREAD

**Issue by sergeyMelentyev** [maxwellito/vivus#59]
I discovered a strange behavior according to browser aspect ratio (width x height).
I am testing on MBP 15 inch (Chrome last version). On full screen mode all callbacks fires, console shows no errors, but nothing happens. SVG disappears as it should be, but drawing does not start. Doing absolutely nothing but decrease browser width (with the same height), drawing starts as it should. I completely remove all my media queries in css (for a rock solid tests), it does not help.

**Comment by sergeyMelentyev** [comment]
I am using alvarotrigo/fullPage.js with HTML5 video background (as a cover). I will continue developing this issue.

**Comment by maxwellito** [comment]
That's strange.. Do you have an example I could try? Can you reproduce the
error on another machine?

Thanks

**Comment by sergeyMelentyev** [comment]
I am sorry for a long reply. I will send more details in a day or so.

**Comment by maxwellito** [comment]
Any updates?

**Comment by inergy** [comment]
I'm seeing this issue too ... it won't do the tracing on some of my svg's unless i shrink the width of the window.  I'll play around with this as well and try to provide some steps/code.  Is there anything that prevents the drawing based on the viewbox or could any other svg attributes affect this?

**Comment by maxwellito** [comment]
This sound serious :-S
Yes please @inergy if you could provide me steps to reproduce this, that would be perfect.
The `inViewport` is only based on ViewBox. But if you're using the version `0.2.1`, there's a little bug with `inViewport` and dynamically loaded SVGs (from the attribute `file`). It's fixed on the latest version, maybe it's this?

**Comment by inergy** [comment]
@maxwellito i'm using 0.2.2 and my svg's are directly in the html... i'll check as soon as I can get time today

**Comment by maxwellito** [comment]
@inergy thanks :)

**Comment by inergy** [comment]
@maxwellito so, here's the starter project i was using to test out vivus: http://bit.ly/1hDd1wU

This is using greensock to control the timeline, but basically there's 2 tracing animations on SVG's that happen... one with the 'ping' logo and another with the 'callaway' logo.  The ping logo will trace just fine, so long as the width of the browser is under 1565px (roughly).  The callaway logo however, must be under about 1150px (again, rough estimate).  I haven't spent much time messing with the viewbox or sizing of the svg's, but that seems like it shouldn't matter as much?

In my timeline, I'm calling 2 functions which use vivus (coffeescript):

```pingTrace = ->
  console.log 'tracing ping logo'
  ($ '#ping').css 'visibility', 'initial'
  new Vivus 'ping',
    type:     'delayed'
    duration: 100

callawayTrace = ->
  console.log 'tracing callaway logo'
  ($ '#callaway').css 'visibility', 'initial'
  new Vivus 'callaway',
    type:     'delayed'
    duration: 100
```

**Comment by maxwellito** [comment]
I see your problem. Your SVGs are very big, and the way Vivus estimate if a SVG is visible is too rigid. Let me explain. Vivus consider an SVG in viewport when this one fits completely in the viewport. Not when it start to be visible. Also, the library only listen on `scroll` events to reevaluate if the element is in the viewport, not on DOM changes or window resize.

The thing is, in your case you know when to trigger the animation start. I would recommend you to use the option `start: 'autostart'`, and the animation should be fine.

**Comment by inergy** [comment]
@maxwellito ahhh ... i didn't even think of that.  That did the trick, and now they are tracing just fine.  Thanks for the clarification!

**Comment by maxwellito** [comment]
@sergeyMelentyev do you think your issue is related to a too large SVG or a lack of `scroll` event?
