### ISSUE TITLE
Add a link

### ISSUE THREAD

**Issue by termoplus** [maxwellito/vivus#63]
Hi,

Could you please help me to add a link to an animated SVG file? Is it possible to add url parameter in this code?

new Vivus('my-svg-id', {
    type: 'delayed',
    duration: 200,
    animTimingFunction: Vivus.EASE
},);

Thanks

**Comment by maxwellito** [comment]
Hi there,
Yes, you just need to provide the attribute `file` with the file link as value. Be careful, there's some restrictions, the file must be on the same domain as the page and cannot be used on a local file (: protocol `file:///`). It's not my lazyness, it's due to security reasons from browsers.

Your HTML
```html
<div id="my-container"></div>
```

Your script
```js
new Vivus('my-container', {
  type: 'delayed',
  duration: 200,
  animTimingFunction: Vivus.EASE,
  file: '/link/to/my.svg'
});
```

**Comment by termoplus** [comment]
Thank you for your help.
You didn't understand me correctly.
I use  file: '/link/to/my.svg' to add an SVG image.

I wand to add URL link that people can click on SVG to open a page or  a website.

is that possible?
thanks

**Comment by maxwellito** [comment]
Oh sorry, my bad.
It's possible but not from the constructor. You must use a listener for that.

```js
var myAnimation = new Vivus('my-container', {
  type: 'delayed',
  duration: 200,
  animTimingFunction: Vivus.EASE,
  file: '/link/to/my.svg'
});

myAnimation.el.addEventListener('click', function () {
    document.location = '//github.com';
});
```

It's not really cool because we loose a bit of accessibility but it works. 

Otherwise I would recommend you to wrap the SVG container into a `<a>` tag.

```html
<a href="//github.com">
    <div id="my-container"></div>
</a>
```

**Comment by termoplus** [comment]
I will try both way and write back. I tried the second option but it didn't work for me.
thanks

**Comment by termoplus** [comment]
it's not working for me.
here is a video for option 1: http://quick.as/PkzBFBbkX
here is a video for option 2: http://quick.as/n8PdCVOR3

here is a live demo for option 2 http://020018.businesscatalyst.com/index.html

I hope you can help
thanks

**Comment by maxwellito** [comment]
You made a mistake on the option 1. You set the listener on `myAnimation` object instead of `svg1` which is your Vivus instance.

**Comment by maxwellito** [comment]
Any luck?

**Comment by termoplus** [comment]
Sorry, I was out of town. 
I tried. no luck :(
here is a link http://020018.businesscatalyst.com/index.html

**Comment by maxwellito** [comment]
Oh.. I realised my mistake. You will need to do it when the SVG is loaded:

```js
var svg1 = new Vivus('svg1', {
  type: 'delayed',
  delay: 100,
  duration: 200,
  start: 'inViewport',
  animTimingFunction: Vivus.LINEAR,
  file: '/assets/enter.svg',
  onReady: function (mySvg) {
    mySvg.el.addEventListener('click', function () {
      document.location = '//github.com';
    });
  }
});


```

**Comment by termoplus** [comment]
it is not working any more :)
http://020018.businesscatalyst.com/index.html

**Comment by maxwellito** [comment]
It's a syntax error. You forgot a comma after the filename.

**Comment by termoplus** [comment]
great!!! 
is it possible to change cursor to hand if SVG has a link?

thanks

**Comment by termoplus** [comment]
it this method not really cool because we loose a bit of accessibility but it works or that's why now?

**Comment by maxwellito** [comment]
In the `onReady` callback, just add this line:

```js
mySvg.el.style.cursor = 'pointer';
```

then your code should look like this:
```js
var svg1 = new Vivus('svg1', {
  type: 'delayed',
  delay: 100,
  duration: 200,
  start: 'inViewport',
  animTimingFunction: Vivus.LINEAR,
  file: '/assets/enter.svg',
  onReady: function (mySvg) {
    mySvg.el.style.cursor = 'pointer';
    mySvg.el.addEventListener('click', function () {
      document.location = '//github.com';
    });
  }
});
```

When I mention loosing accessibility, I'm talking about respecting HTML standards instead of mimic the natural behavior in JavaScript. For example, a user cannot make a right click on your SVG, then choose `Open link in a new page`. But you don't really have the choice. Don't worry about it.

**Comment by maxwellito** [comment]
Any updates?

**Comment by termoplus** [comment]
Great!
I meant is it possible to be a hand cursor only if there is a link in the SVG.
Now it's all the time :(

Thank you for your help. I appreciate it.
