### ISSUE TITLE
My svg start  at the begining

### ISSUE THREAD

**Issue by Szymon-dziewonski** [maxwellito/vivus#64]
Hello, I'm wondering why my svg start at the begining even i put 

var myVivus = new Vivus('Layer_1');
    var myVivus2 = new Vivus('Layer_2');
    myVivus.reset().stop();
    myVivus2.reset().stop();

and it works for chrome but doesn't work for other browsers, so animation fires at the begining after load, how can I stop drawing at the begining and only fire it up at ,y will ? 

btw. thanks for great work :)

**Comment by maxwellito** [comment]
By default, the animations start while they are completely in the viewport. I presume your are at the top of your page. Set the option `start: 'manual'` then trigger play when you want.

Can you show me an example please?

**Comment by Szymon-dziewonski** [comment]
Im building big website and I cant show you it now, but your solution is working so I appreciate that a lot 

<svg version="1.1" id="Layer_2" class="kraftenSVG" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"  viewBox="0 0 459 361" style="new 0 0 459 361;">
   <path d="M98.5,174.8c0,0-71.5,4-73.3-42.3S9,18.3,82.5,16.8s353.8,0,353.8,0"/>
</svg>

And settings like above, but your setting work like a charm ! Thank you very much :)
