### ISSUE TITLE
Prevent path from animating

### ISSUE THREAD

**Issue by stepladder** [maxwellito/vivus#69]
I've got an intricate SVG image with many paths, I only want one path to animate.

The path I want to animate is a stroke. The rest of the paths are filled shapes.

I find if I make the whole SVG strokes, the animation works, but if the animation is made up of fill paths and strokes, the animation doesn't work at all.

I would expect all the shape paths to stay static, and the stroke to animate, that's what I want.

Is there a way I can label a path to not animate? or tell all paths to not animate except for one?

Many thanks,

**Comment by maxwellito** [comment]
Hi there,

I'm sorry, for now I don't have a solution to your issue. This has been mentioned in a previous issue.
I think I will implement a tag to disable animation on `path` elements with the tag `vivus-ignore`.

If you want to implement it to your version, just change `this.el.querySelectorAll('path');` (line 504 in the unminified version) to `this.el.querySelectorAll('path:not([vivus-ignore])');`.

Then you will be able to disable the paths you want.

**Comment by stepladder** [comment]
Great, thanks!
