### ISSUE TITLE
How can i fill svg after animation ?

### ISSUE THREAD

**Issue by beaver-creation** [maxwellito/vivus#71]
Hey all !

My svg animation work with vivus.js but after animation is complete, how can i fill my svg ?

Thanks for reply :)

**Comment by maxwellito** [comment]
Hi,
If you're using inline SVG (:where the entire SVG is defined in your HTML) you can use the trick mentioned in the [hacks.md](https://github.com/maxwellito/vivus/blob/master/hacks.md)

**Comment by beaver-creation** [comment]
Thank for reply Maxwellito.

Yes but in the descriptions of Vivus.js it is written : 
     • All elements must have a stroke property and cannot be filled. This is because the animation only looks to progressively draw strokes and will not check for filled colours. For example: fill: "none"; stroke: "#FFF";

So where can i set the color of my path ?

**Comment by maxwellito** [comment]
Well, except here.
In this case you can keep the `fill` property in your SVG. The little hacks consist to make it transparent from the start, then make it appear once the animation over.

**Comment by maxwellito** [comment]
Any luck?
If you want some help, just create a jsfiddle and post the link :)

**Comment by beaver-creation** [comment]
Thanks Maxwellito, it's work fine :) But finally i've use an other jQuery plugin. But i think i use this one for my personal projects :)

**Comment by maxwellito** [comment]
Ok, if you need any help join the conversation on [Gitter](https://gitter.im/maxwellito/vivus) :)
