### ISSUE TITLE
Custom Callback for manual .play()

### ISSUE THREAD

**Issue by katerlouis** [maxwellito/vivus#74]
Hello, 
I need a custom callback everytime I .play() the animation. One for initial draw for example, one for reverse drawing, and one for drawing it back, and maybe some more- Doing all this with the one callback declared in the constructor is very inconvenient for me

lines.play(function() { });
lines.play(200, function() { });
all not working, and Docs aren't telling anything about it.

I hope you can give me a hint on how to add custom callbacks :)

Thanks,
Louis

**Comment by maxwellito** [comment]
Hi there,
Yes, the method `.play()` doesn't accept a second parameter as callback. What you can do, is before to play, you can set the property `.callback` on your Vivus object.

```js
lines.callback = function () {...}
lines.play(1);
```

Post your code on JSfiddle (or other) if you need some help.

**Comment by katerlouis** [comment]
Nice, man! That's simple- thx very much.
Guess with more knowledge in plugin structure I could have figured it out myself- but now it's public! :DMaybe you update your Docs and get a lil bit more specific in some points like this one.

Is there a more convenient way to set default options than writing: var vivusOptions = { ... };?
I know it's off the topic, but I don't know if it's worth to make a new issue for this one, either.

Thanks!

**Comment by maxwellito** [comment]
Nope, there's no way to force default options. The only thing you can do is to define your default options at the start in an object, then merge it. Example with jQuery.

```js
var defaultOptions = {
  duration: 200,
  type: 'oneByOne'
};

new Vivus(
  'myTag', 
  $.extend({}, defaultOptions, {type: 'delayed'})
);
```

It's not very handy, I admit it. It's something I could think of for the future versions.
