### ISSUE TITLE
Handy way / shortcut for reverse drawing and back again?

### ISSUE THREAD

**Issue by katerlouis** [maxwellito/vivus#75]
I want to draw the icon in reverse and directly afterwards "back to normal"-

Is there a shorter way than: 
```
.callback = function() { ... .play(); } 
.play(-1).callback = function() { // prevent recursive :D } 
```

It feels like .play(-1) is not using the duration declared in the constructor.
Sorry for my need of help :)

Thans!
Louis

**Comment by maxwellito** [comment]
The speed should be the same. Create a JSfiddle to let me check this please.

For this problem you can use the method `getStatus` which I forgot to document :-S
This method return : `start`, `progress` or `end`

```js
var myVivus = new Vivus('myTag', {}, function (myVivus) {
  if (myVivus.getStatus() === 'start')
    myVivus.play(1);
});
myVivus.finish().play(-1);
```
