### ISSUE TITLE
Dots appear before animation starts

### ISSUE THREAD

**Issue by PeterWooster** [maxwellito/vivus#79]
I've encountered a strange problem.  Dots appear at the end of paths before they paint.  This was reported on another SVG painting program in issue https://github.com/camoconnell/lazy-line-painter/issues/36.   They were seeing this on Safari and Firefox, I'm seeing it on Chrome Version 47.0.2526.106 (64-bit) on Mac OS 10.9.5.

You can see these dots on your page https://maxwellito.github.io/vivus/ on the 't' in 'there'.

**Comment by PeterWooster** [comment]
I just tested this on an older version, Chrome Version 46.0.2490.86 and the dots don't appear. UIpdating to the latest version brought them back. These tests were done on Mac OS 10.11

**Comment by old9** [comment]
Same here Chrome 47.0.2526.106 on Windows

**Comment by maxwellito** [comment]
Thanks about the warning. I guess Chrome has changed some parts of SVG treatment, which give me headaches about `dashOffset`. This is why the `dashGap` is for in the Vivus options. I guess I'll have to find out which correct value to use. I keep you posted :)
Thanks

**Comment by maxwellito** [comment]
Ok, I changed the values Vivus set on `strokeDashoffset` and `strokeDasharray` to add some gap before and after. 
Demo case available on http://maxwellito.github.io/drafts/vivus-issue-79/
Chrome, Firefox and Safari seems to display it without glitches. I'll try on other browsers during the week (previous Chrome and lovelay Internet Explorers).

Here is a `diff` for interested people.

```diff
@@ -446,7 +446,7 @@ Vivus.prototype.setOptions = function (options) {
   this.isIE        = (window.navigator.userAgent.indexOf('MSIE') !== -1 || window.navigator.userAgent.indexOf('Trident/') !== -1 || window.navigator.userAgent.indexOf('Edge/') !== -1 );
   this.duration    = parsePositiveInt(options.duration, 120);
   this.delay       = parsePositiveInt(options.delay, null);
-  this.dashGap     = parsePositiveInt(options.dashGap, 2);
+  this.dashGap     = parsePositiveInt(options.dashGap, 1);
   this.forceRender = options.hasOwnProperty('forceRender') ? !!options.forceRender : this.isIE;
   this.selfDestroy = !!options.selfDestroy;
   this.onReady     = options.onReady;
@@ -525,13 +525,10 @@ Vivus.prototype.mapping = function () {
     }
     totalLength += pathObj.length;
     this.map.push(pathObj);
-    path.style.strokeDasharray  = pathObj.length + ' ' + (pathObj.length + this.dashGap);
-    path.style.strokeDashoffset = pathObj.length;
+    path.style.strokeDasharray  = pathObj.length + ' ' + (pathObj.length + this.dashGap * 2);
+    path.style.strokeDashoffset = pathObj.length + this.dashGap;
+    pathObj.length += this.dashGap;

-    // Fix IE glitch
-    if (this.isIE) {
-      pathObj.length += this.dashGap;
-    }
     this.renderPath(i);
   }

@@ -640,7 +637,7 @@ Vivus.prototype.trace = function () {
     progress = this.pathTimingFunction(Math.max(0, Math.min(1, progress)));
     if (path.progress !== progress) {
       path.progress = progress;
-      path.el.style.strokeDashoffset = Math.floor(path.length * (1 - progress));
+      path.el.style.strokeDashoffset = path.length * (1 - progress);
```

**Comment by PeterWooster** [comment]
Hi,

Thanks for the update.  It’s works, no more dots, but the last line in this image doesn’t draw properly:  http://silvermapleweb.com/jstest/ <http://silvermapleweb.com/jstest/>, it ends up about half the length shown when you refresh.  The code is set up to draw on click.

/peter

**Comment by maxwellito** [comment]
Hi @PeterWooster 
Thanks for the feedback and nice catch!
I realised the issue was coming from a little mistake in the algorithm. I was calculating the total length of all path but without the `dashGap`. My draft page still works, and your demo is now working :)

Here is the diff https://github.com/maxwellito/drafts/commit/49435e6997f26aff354f14851297d2b575d751ee

**Comment by PeterWooster** [comment]
Thanks,  

I’ll give it a try on our system tomorrow.

/peter

**Comment by j2p2f2** [comment]
Hey @maxwellito! Your fix worked perfectly. Thank you for posting it.

**Comment by maxwellito** [comment]
Sorry for the long delay :-S
But here is the [v0.3.0](https://github.com/maxwellito/vivus/tree/dev) ready to be released. It's on the dev branch. I added a manual test page to check this kind of glitches in the future. I don't know if somebody would like to test it quickly, but feedback is always welcome. Otherwise it should be published in the next days.
