### ISSUE TITLE
Loop Animations

### ISSUE THREAD

**Issue by felixdorner** [maxwellito/vivus#83]
Great plugin! Works like a charm. 

Not really an issue, but a question: Is it possible to loop animations infinitely?

**Comment by maxwellito** [comment]
Hallo :)

Well, if by infinite you mean: draw, undraw, draw, undraw, draw.... yeah it is.
In the callback of animation end, just check for the status use `play()` with a good value.

```js
new Vivus('hi-there', {}, function (myVivus) {
  myVivus.play(myVivus.getStatus() === 'end' ? -1 : 1);
})
```

*You can run this code on the demo page.*

Is it what you're looking for?

**Comment by juhamust** [comment]
Same approach works also for lopping in one direction:
```js
new Vivus('hi-there', {}, myVivus => {
  if (myVivus.getStatus() === 'end') {
    myVivus.reset().play();
  }
});
```

**Comment by xhostar** [comment]
Hi:
and... it's possible to make a short pause before playing again?

I've tried this:

```
new Vivus('hi-there', {}, function (myVivus) {
  setTimeout(function() {
    myVivus.play(myVivus.getStatus() === 'end' ? -1 : 1);
  }, 500);
})
```
but it does not work correctly because sometime the animation breaks...

**Comment by Asg21** [comment]
> ```js
> new Vivus('hi-there', {}, myVivus => {
>   if (myVivus.getStatus() === 'end') {
>     myVivus.reset().play();
>   }
> });
> ```

it's so fast
