### ISSUE TITLE
data-async on groups

### ISSUE THREAD

**Issue by sqrtroot** [maxwellito/vivus#84]
Hi there, thanks for this awesome plugin :D.
I would like to know if it's possible to set the data-async attribute on group svg tags <g>

sqrtroot

**Comment by maxwellito** [comment]
Hi @sqrtroot 
Thanks for these kind words. 
Unfortunately, it's not possible. I've been thinking about it when I started the project, but never did it. It could be very useful for `scenario` and `scenario-sync`. I'll try to implement in in the next versions.
Sorry about that.

Max
