### ISSUE TITLE
callback for drawing paths

### ISSUE THREAD

**Issue by albaluca87** [maxwellito/vivus#85]
Hi, first of all thank you for this script!
This is not an issue but only a question!
I have an svg with multiple paths and i want to achieve this result:
draw one path..then wait for some data (like ajax calls or other operations)..draw another path and so on.
Is it possible this kind of custom animation?

**Comment by maxwellito** [comment]
Hallo!!
Thanks for these kind words, even if I don't understand this general keen interest into this little library.

Anyway.
I'm sorry to tell that Vivus cannot do this for now. And it make me feel sad to that this library cannot do what people would like to. So I tried to find out a hacky way which could be easy to use and it was pretty easy actually :)
So here is the trick.

For now, the more appropriate `options` are using type `oneByOne` and start `manual`. Which is what you will have to use to create your Vivus object.

```js
var myVivus = new Vivus('yourSvgId', {
  type: 'oneByOne',
  start: 'manual'
});
```

Then you gonna add this little extension for Vivus. Do it only once! I mean there will be no issues or conflicts, but only a useless duplication of code.

```js
Vivus.prototype.next = function () {
  if (this.currentStep === undefined) {
    this.currentStep = 0;
  }
  else if (this.currentStep + 1 === this.map.length) {
    this.currentStep = -1;
    this.play(-1);
    return;
  }
  else {
    this.currentStep += 1;
  }

  var currentPath = this.map[this.currentStep];
  this.frameLength = currentPath.startAt + currentPath.duration;
  this.play();
}
```

Then now, you can directly call the method `next()` on your object. This will draw the next path.
I made it in a way that at the end it rewind the animation to start, then the method can be called again.

```js
$.get('/something.json', function (data) {
  myVivus.next();
});
```

I hope this trick will work for you. 
Ask if you need! :)

**Comment by albaluca87** [comment]
Nice trick, It's just what i needed :)
What about two methods, next() and previous()?
next() to draw forward and previous() to rewind the last path.
I'm trying to achieve the previous() call myself but without success, any tips?

Thanks

**Comment by maxwellito** [comment]
Dammit! The 'previous' method will ask a bigger refactor. It won't be as
easy as 'next'. You will have to override some core methods. I should have
some free time this weekend to think about it :)

**Comment by albaluca87** [comment]
@maxwellito  Ok I'll wait your solution! :) thanks

**Comment by maxwellito** [comment]
Ok it was a massive rewrite, and it cannot be done via only method override (because it use functions from the scope where Vivus is created).
Check at http://maxwellito.github.io/drafts/vivus-issue-85/

```js
Vivus.prototype.next = function () {
  if (this.currentStep === undefined) {
    this.currentStep = 0;
  }
  if (this.currentStep === this.map.length) {
    return;
  }
  this.currentStep += 1;
  this.setMilestoneAndGo();
};

Vivus.prototype.previous = function () {
  if (!this.currentStep) {
    return;
  }

  this.currentStep -= 1;
  this.setMilestoneAndGo();
};

Vivus.prototype.setMilestoneAndGo = function () {
  if (this.currentStep) {
    var currentPath = this.map[this.currentStep - 1];
    this.milestone = currentPath.startAt + currentPath.duration;    
  }
  else {
    this.milestone = 0;
  }

  this.play((this.milestone - this.currentFrame > 0) ? 1 : -1);
};

Vivus.prototype.drawer = function () {
  var self = this;

  if (Math.abs(this.milestone - this.currentFrame) <= Math.abs(this.speed)) {
    this.currentFrame = this.milestone;
    this.handle = null;
    if (this.currentFrame >= this.frameLength) {
      this.callback(this);
    }
  }
  else {
    this.currentFrame += this.speed;
    this.handle = requestAnimFrame(function () {
      self.drawer();
    });
  }
  this.trace();
};
```

**Comment by albaluca87** [comment]
Thanks a lot works great! :+1:

**Comment by trippo** [comment]
How to do this with the last version?
