### ISSUE TITLE
Add delay to inViewport

### ISSUE THREAD

**Issue by jeffceriello** [maxwellito/vivus#91]
Hi,

Is it possible to add a delay to the inViewport option? Ideally it would be useful to have the svg start animating for example 100px above the bottom of viewport.

Is that achievable?

Thank you,
Jeff

**Comment by jeffceriello** [comment]
I have tried that by resetting the animation and playing when in viewport with offset 50% using the plugin jquery waypoint

I add the svg like this

`var tick1 = new Vivus('tick1', {file: 'img/tick.svg'});`

but then when I reset it with `tick.reset();` I get an error `TypeError: this.map is null`

Then I wanted to start the animation like this

```
var waypoint = new Waypoint({
		element: document.getElementById('tick1'),
		handler: function(direction) {
		    tick1.play(40);
		},
		offset: '5%' 
	})
```
How can I fix the reset() error?
Would that work?

Thank you

**Comment by maxwellito** [comment]
Hallo,

1. I think your `.reset()` is triggering an error because you;re calling it when the SVG in loaded and mapped by Vivus. You have to wait the call of `onReady` callback to start performing actions to your Vivus instance.

2. I'm afraid there's no trick about the viewport. Maybe the `offset` can work but I haven't tested. What I would recommend you is to set the start on `manual` then make your own listener to trigger the call to `play()`.

```js
var tick1 = new Vivus('tick1', {
  file: 'img/tick.svg',
  start: 'manual',
  onReady: function (vivusObj) {
    window.addEventListener('scroll', function () {
      // test if vivusObj.el is in your viewport conditions
      // ...if so vivusObj.play();
    })
  }
});
```

I hope this help

**Comment by jeffceriello** [comment]
Hi,

Thank you for your help on this! 

The offset works fine with your snippet. Unfortunately the `vivusObj.play();` doesn't draw the object but instead it just makes it appear instantly. Is there a solution to this or should I just forget about this approach? Here is my entire code:

```
var tick1 = new Vivus('tick1', {
	  file: 'img/tick.svg',
	  start: 'manual',
	  onReady: function (vivusObj) {
        var waypoint = new Waypoint({
			element: document.getElementById('tick1'),
			handler: function(direction) {
			    vivusObj.play(40);
			},
			offset: '50%' 
		})
	  }
	});
```

**Comment by maxwellito** [comment]
Here is your problem : `vivusObj.play(40);`
You set the speed at 40, while the normal one is 1.
Just call play without parameters : `vivusObj.play();`
Should work :)

**Comment by jeffceriello** [comment]
Oh ok, that worked! I thought I could pass the speed in the function.

It works fine now, thank you so much :)

**Comment by maxwellito** [comment]
Brilliant! :)
