### ISSUE TITLE
Animate to a certain % of the animation and control the animation using events

### ISSUE THREAD

**Issue by prashantsani** [maxwellito/vivus#92]
Hello.
I m planning to use this with a scrollbased library.
Is it possible to animate it to a certain percentage, for instance every single time a user scrolls, i can animate this to a certain % of the animation based on scroll position.

Adding setFrameProgress does not animate to states. 

for instance : 
```javascript
var newVivusAnim =new Vivus('someDiv', {duration: 200, type: 'async'}, function(){console.log('vivus done')});

newVivusAnim
.stop()
.reset()
.setFrameProgress(0.3)
```

The SVG fails to animate when below code is applied again  on some event (can be a scroll event)

`quoteTextVivus.setFrameProgress(0.3)`

**Comment by maxwellito** [comment]
Hello,
Sorry for the late reply.
I'm afraid, the current version of Vivus cannot give you this freedom. However, I recommend you to have a look to the [issue 85](https://github.com/maxwellito/vivus/issues/85#issuecomment-180811263). By using this code, you will be able to manipulate the property `milestone` of your Vivus instance. This property represent the frame to reach and stop at.

```js
var newVivusAnim = new Vivus('someDiv', {
    duration: 200,
    type: 'manual'
});

newVivusAnim.milestone = 100;
newVivusAnim.play();
// This 'should' play your animation to the half (because 200/100 = .5).
```

**Comment by lepoi** [comment]
200/100 = 2
