### ISSUE TITLE
how can i get the length of path element?

### ISSUE THREAD

**Issue by summerGreenTea** [maxwellito/vivus#93]
i need to get the length of path element for control the process of animation。who can give me some idea.  thanks。

**Comment by maxwellito** [comment]
Hello,
Simply use the method `.getTotalLength()` on your Path element. It should return the length.

```js
// Like that
var length = document.getElementById('the-id-of-your-path').getTotalLength();
```

**Comment by summerGreenTea** [comment]
thank you for the nice answer
