### ISSUE TITLE
Cannot animate an InkScape exported SVG

### ISSUE THREAD

**Issue by IonicaBizau** [maxwellito/vivus#96]
This is a great library! :sparkles: 

However, I have trouble animating an SVG image exported by InkScape. It is loaded successfully on the page, but there is no animation. I'm not sure what I'm doing wrong.

It does work using the demo SVG, tho... Where to start debugging this?

**Comment by maxwellito** [comment]
Hello!
Well if you could make a jsfiddle of your code, or giving more info that
could help :)
Even posting your SVG just to have a look.
Do you have an error in your browser console (:dev tools)?

Thanks

2016-04-04 4:52 GMT+01:00 Ionică Bizău <notifications@github.com>:

**Comment by IonicaBizau** [comment]
@maxwellito I created a test svg file and tried it [here](http://jsfiddle.net/dybaaqf8/). You can see that the animation is not there... I have no idea why.

**Comment by maxwellito** [comment]
Your SVG path were filled, and not based on strokes. Which is on what Vivus
animate SVGs.
I made a CodePen with the updated code, and added a hacks to fill the paths
at the end (from hacks.md).
http://codepen.io/maxwellito/pen/eZeYgw

2016-04-04 10:21 GMT+01:00 Ionică Bizău <notifications@github.com>:

**Comment by IonicaBizau** [comment]
@maxwellito Ah, got it! Thanks a lot! :cake:
