### ISSUE TITLE
Rewind reverse direction

### ISSUE THREAD

**Issue by unetics** [maxwellito/vivus#97]
HI i was wondering if there was any way to remove itself the same direction it was drawn?

**Comment by maxwellito** [comment]
Hi there,
I'm afraid this is not possible except if you hack the library. I think
this issue has already been posted.

**Comment by jzlosman** [comment]
Is this what you were looking to do? 

[fiddle](https://jsfiddle.net/41L4nej5/4/)

I originally set it up to be an endless loop for loading, like this.

[fiddle](https://jsfiddle.net/41L4nej5/5/)

**Comment by charliecduong** [comment]
How do you rewind the stroke and fill?

**Comment by justgeek** [comment]
@jzlosman what about the callback function, have you removed it ? Great Job btw, Thank You.
