### ISSUE TITLE
Animation style per path?

### ISSUE THREAD

**Issue by Artusamak** [maxwellito/vivus#98]
Hi, thanks for your library, it's really easy to use.
I was wondering if it was possible to change the style of animation per path. It's not documented in your doc and it seems to be possible. I just didn't find how.

Thanks for your help!

**Comment by maxwellito** [comment]
Hallo,

I'm not sure to get what you mean. Do you want a different
pathTimingFunction for every path?

**Comment by Artusamak** [comment]
Yes, that's the idea.

**Comment by maxwellito** [comment]
I'm afraid this is not possible without hacking the library. I can help you
with it but only in a week. I'm currently away from any computers, and
coding on a phone is a joke.

**Comment by Artusamak** [comment]
No rush there. :)
I guess that having a new attribute to add to the path such as pathTimingFunction="ease-in" would be how you specify the path animation style.

**Comment by maxwellito** [comment]
If using attribute like `pathTimingFunction="ease-in"` is not a problem for you, it sounds doable. Do you want to restrict this to Vivus animation function, or custom ones too?

**Comment by Artusamak** [comment]
I guess that Vivus animations is a good start. I didn't dive into the custom animation functions to be honest.

**Comment by maxwellito** [comment]
Ok, sorry for the delay but here the hack. The diff is based on `src/vivus.js` (you will to compile again after)

```diff
263c263
<   var i, paths, path, pAttrs, pathObj, totalLength, lengthMeter, timePoint;
---
>   var i, animFn, paths, path, pAttrs, pathObj, totalLength, lengthMeter, timePoint;
271a272,273
>     animFn = path.getAttribute('timing-function');
>     animFn = Vivus[animFn] || this.pathTimingFunction;
274c276,277
<       length: Math.ceil(path.getTotalLength())
---
>       length: Math.ceil(path.getTotalLength()),
>       timingFunction: animFn
394c397
<     progress = this.pathTimingFunction(Math.max(0, Math.min(1, progress)));
---
>     progress = path.timingFunction(Math.max(0, Math.min(1, progress)));
```

And here is the SVG code:

```html
<svg ...>
  <path timing-function="EASE_IN" d="..."/>
  <path timing-function="EASE_OUT" d="..."/>
  <path d="..."/>
  <path timing-function="EASE_OUT_BOUNCE" d="..."/>
</svg>
```

I stay here is you need help.
