### ISSUE TITLE
Callback still being called after instanced destroyed

### ISSUE THREAD

**Issue by schnerd** [maxwellito/vivus#99]
For starters–awesome library!

We recently noticed that Vivus will still execute it's done callback, even if we've called `destroy()` on the instance.

```js
function callback() {
    console.log('this will still be called even though the instance was destroyed');
}

var v = new Vivus('svg_logo', { type: 'oneByOne' , start: 'autostart' }, callback);
v.destroy();
```

Is this the intended functionality? From a developer UX standpoint, it seems logical to me that instance should stop all asynchronous operations after you `destroy()` it. It has caused some issues for our team because we destroy vivus instances when unmounting components in a React application, but the component still ends up executing code after it is unmounted due to the vivus callback.

Here's a jsfiddle: http://jsfiddle.net/xxqmLgj0/2/

I've submitted a pull request with a test and proposed fix: #100

**Comment by maxwellito** [comment]
Thanks :) it's merged!
